import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {renderGuidedExecution} from '../src/m26/workflows/session-ui.js';
import {renderSessionsRoute} from '../src/m26/modules/route-render.js';
const clientId='57339e70-7a99-48d6-820f-7d4a51f89d9d';
function prep(){return {kind:'next-session-preparation',clientId,session:{id:'session-next',title:'Fuerza B',status:'publicado',startable:true,source:'published'},appointment:null,iri:null,progress:{plannedSessions:4,completedSessions:3,adherence:.75,adherencePercent:75,averageRpe:7,lastExecutionRpe:8,lastExecutionAt:'2026-10-07T10:00:00Z',latestCheckinAt:null,latestCheckin:null,checkinAverage:null,dataQuality:'media',unconfirmedExecutions:0},lastExecution:{id:'exec-prev',sessionId:'session-prev',completedAt:'2026-10-07T10:00:00Z',feedback:{sessionRpe:8,comment:'Correcta',pain:true,painNotes:'Molestia leve'}},exerciseMemory:[],decisions:{total:0,openCount:0,closedCount:0,overdueCount:0,dueTodayCount:0,open:[],recentClosed:[],needsReview:null},reviewRequired:true,reviewReasons:[{kind:'pain',label:'La última sesión registró dolor; revisa el contexto antes de decidir.'}],evidence:{dataQuality:'media',exerciseMemories:0,openDecisions:0,hasIri:false,hasRecentExecution:true,hasRecentCheckin:false},safety:{automaticLoadChange:false,automaticExerciseChange:false,automaticClinicalDecision:false,coachConfirmationRequired:true,note:'Sin automatismos.'}};}
test('sesión Coach completada aterriza en el workspace de decisión exacto',()=>{const html=renderGuidedExecution({execution:{id:'exec-done',clientId,sessionId:'session-done',status:'completed',syncStatus:'clean',accumulatedActiveMs:3600000,results:{},queue:[],feedback:{sessionRpe:7,comment:'Bien',pain:false,painNotes:''}},session:{id:'session-done',clientId,title:'Fuerza A'},role:'coach'});assert.match(html,/data-m26-coach-action="true"/u);assert.match(html,/data-m26-target-area="expediente"/u);assert.match(html,/data-m26-target-focus="action-outcome"/u);assert.match(html,/>Revisar seguimiento</u);});
test('revisión pre-sesión Coach usa handoff exacto; Admin conserva navegación normal',()=>{const common={kind:'sesion',serviceKind:'training',serviceActive:true,canBuild:true,sessions:[],sessionCounts:{published:1},executions:[],nextSessionPreparation:prep()};const coach=renderSessionsRoute({...common,role:'coach'});const admin=renderSessionsRoute({...common,role:'admin'});assert.match(coach,/data-m26-coach-action="true"[^>]*data-m26-client-id=/u);assert.match(coach,/data-m26-target-focus="action-outcome">Revisar seguimiento antes de entrenar/u);assert.match(admin,/data-m26-area="expediente">Revisar seguimiento antes de entrenar/u);assert.doesNotMatch(admin,/data-m26-target-focus="action-outcome">Revisar seguimiento antes de entrenar/u);});
test('shell usa whitelist cerrada y espera el render real',()=>{const source=fs.readFileSync('src/m26/shell/shell-controller.js','utf8');assert.match(source,/COACH_ACTION_FOCUS_TARGETS=Object\.freeze/u);assert.match(source,/Object\.prototype\.hasOwnProperty\.call\(COACH_ACTION_FOCUS_TARGETS,key\)/u);assert.match(source,/root\.addEventListener\?\.\('m26:shell-rendered',onRendered,\{once:true\}\)/u);assert.match(source,/return targetFocus\?focusCoachActionTarget\(targetFocus\):false/u);assert.match(source,/cancelTargetFocus\?\.\(\)/u);});
