import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {normalizeWearableDailyRecord,parseWearableExportText,parseWearableExportTextAsync} from '../src/m26/wearables/normalization.js';
import {buildWearableViewModel} from '../src/m26/wearables/view-model.js';
import {wearableZeroCostPolicy} from '../src/m26/wearables/free-policy.js';
const read=(file)=>fs.readFileSync(file,'utf8');
const clientId='11111111-1111-1111-1111-111111111111';

test('RC44.2 representa la fila remota real record_date',()=>{const normalized=normalizeWearableDailyRecord({record_date:'2026-08-04',provider:'normalized_file',steps:7500,active_minutes:42,sleep_minutes:450,resting_heart_rate:58,hrv_ms:48,active_energy_kcal:520,workout_minutes:35,quality:'media'},{clientId});assert.equal(normalized.ok,true);const vm=buildWearableViewModel({records:[normalized.value],role:'client',now:new Date('2026-08-05T12:00:00Z'),scope:{}});assert.equal(vm.dailyRecords.length,1);assert.equal(vm.dailyRecords[0].date,'2026-08-04');assert.equal(vm.dailyRecords[0].metrics.steps,7500);assert.equal(vm.dailyRecords[0].metrics.sleepMinutes,450);});

test('RC44.2 importa CSV europeo y segundos de actividad sin bloquear',async()=>{const csv='activity_date;moving_time;calories;steps\n2026-08-04;2100;520;7500';const sync=parseWearableExportText(csv,{fileName:'activities.csv',clientId,provider:'strava'});assert.equal(sync.accepted[0].metrics.workoutMinutes,35);let yields=0;const asyncResult=await parseWearableExportTextAsync(csv,{fileName:'activities.csv',clientId,provider:'strava',scope:{scheduler:{yield:async()=>{yields+=1;}}}});assert.equal(asyncResult.accepted.length,1);assert.equal(yields,1);});

test('RC44.2 deja todas las fuentes importables y bloquea conexiones ficticias',()=>{for(const provider of ['normalized_file','health_connect','samsung_health','apple_health','strava','fitbit','oura','garmin_connect'])assert.equal(wearableZeroCostPolicy(provider).fileImportAllowed,true,provider);assert.equal(wearableZeroCostPolicy('health_connect').tier,'free_development');assert.equal(wearableZeroCostPolicy('samsung_health').tier,'free_development');assert.equal(wearableZeroCostPolicy('strava').tier,'free_registration');assert.equal(wearableZeroCostPolicy('garmin_connect').productionAllowed,false);assert.equal(wearableZeroCostPolicy('strava').productionAllowed,false);});

test('RC44.2 muestra historial y usa solo la navegación móvil canónica',()=>{const route=read('src/m26/modules/route-render.js');const css=read('src/m26/rc44/rc44.css');assert.match(route,/Últimos registros diarios/u);assert.match(route,/Plan gratuito de integraciones/u);assert.match(route,/Todo lo gratuito que puede usarse ahora/u);assert.match(route,/Ninguna fuente aparece como conectada/u);assert.match(route,/No disponible/u);assert.match(route,/<details class="m26-panel m26-optional-section"><summary>Dispositivos e integraciones opcionales/u);assert.ok(css.includes('.m26-client-bottom-nav-layer{display:none!important}'));assert.ok(css.includes('.m26-client-route-shell{min-height:0!important;padding-bottom:0!important}'));assert.ok(!route.includes('renderClientBottomNav(vm)}</div>'));assert.ok(route.includes('.tsv,application/json'));assert.match(route,/Conexión directa: No disponible\./u);assert.match(route,/No está conectada ni comparte datos/u);assert.doesNotMatch(route,/OAuth|canje de tokens|backend|Arquitectura preparada/u);});

test('RC44.2 registra build reproducible y nueva caché PWA',()=>{const pkg=JSON.parse(read('package.json'));const finalizer=read('scripts/finalize_rc442_candidate.mjs');assert.ok(pkg.scripts['validate:rc442:local']);assert.equal(pkg.scripts['build:rc442:canary'],'npm run build:rc44:canary && node scripts/finalize_rc442_candidate.mjs');assert.match(finalizer,/m26-rc44-2-stable-wearables-canary-v1/u);assert.match(finalizer,/installShell\(\)\.then\(\(\)=>self\.skipWaiting\(\)\)/u);assert.match(finalizer,/RC442_BUILD_VERIFICATION\.json/u);});
