import test from 'node:test';
import assert from 'node:assert/strict';
import {createApplicationContext,switchApplicationContext} from '../src/m26/shared/application-context.js';
import {createPermissionSet,hasCapability} from '../src/m26/shared/permission-set.js';
import {normalizeApplicationContextExtension,filterSnapshotForAssignmentScope} from '../src/m26/shared/integration-context.js';
import {createAdminState,projectAdminSnapshot,M26_ADMIN_COLLECTION_KEYS} from '../src/m26/admin/admin-state.js';
import {createAdminCommand,M26_ADMIN_COMMAND_TYPES} from '../src/m26/admin/command-catalog.js';
import {createAdminCommandService} from '../src/m26/admin/service.js';
import {createCommunicationState,projectCommunicationSnapshot} from '../src/m26/communication/state.js';
import {createCommunicationCommand,M26_COMMUNICATION_COMMAND_TYPES} from '../src/m26/communication/command-catalog.js';
import {createCommunicationService} from '../src/m26/communication/service.js';
import {navigationForRole,roleHome,areaAllowedForRole} from '../src/m26/shell/navigation.js';
import {createProductionState,stateFromBootstrap} from '../src/m26/production-state.js';
import {createShellViewModel} from '../src/m26/shell/shell-view-model.js';
import {createRouteViewModel} from '../src/m26/modules/route-view-model.js';

const org='00000000-0000-4000-8000-000000000140';
const capabilities=['organization.read','organization.settings.manage','user.read_summary','user.manage_status','role.read','role.manage','assignment.read','assignment.manage','client.lifecycle.read','client.lifecycle.manage','appointment.manage_global','operation.read_global','operation.manage_global','message.read','message.manage_templates','automation.read','automation.manage','analytics.read','audit.read'];
function rawAdmin(){return {ok:true,organization:{id:org,name:'IBERFIT',revision:1},permissions:capabilities,serverTime:'2026-08-01T20:00:00Z',data:{organizationUsers:[{id:'U1',userId:'U1',name:'Carlos',status:'active',roles:['coach','admin'],token:'NO'}],applicationRoles:[],coachProfiles:[],coachClientAssignments:[],leads:[],clientLifecycle:[],operationalTasks:[],notificationTemplates:[],notificationDeliveries:[],automationRules:[],auditEvents:[]},analytics:{activeClients:0},revision:1};}
function admin(){return projectAdminSnapshot(rawAdmin(),{id:'U1',role:'admin'});}

test('cambiar a Admin limpia cliente y permisos Coach',()=>{const current=createApplicationContext({application:'coach',activeRole:'coach',organizationId:org,selectedClientId:'C1',permissions:['client.read_assigned'],sessionId:'S1'});const next=switchApplicationContext(current,'admin',{role:'coach',authorizedRoles:['coach','admin']});assert.equal(next.selectedClientId,null);assert.deepEqual(next.permissions,[]);});
test('permission set rechaza comodines',()=>assert.throws(()=>createPermissionSet({capabilities:['organization.*']}),/CAPABILITY_INVALID/));
test('capabilities no se amplían localmente',()=>{const p=createPermissionSet({capabilities:['audit.read'],scopeType:'organization',organizationId:org});assert.equal(hasCapability(p,'audit.read'),true);assert.equal(hasCapability(p,'role.manage'),false);});
test('scope Coach filtra clientes y sesiones asignadas',()=>{const snapshot={data:{clients:[{id:'C1'},{id:'C2'}],sessions:[{id:'S1',clientId:'C1'},{id:'S2',clientId:'C2'}],coachAvailability:[{id:'A'}]}};const filtered=filterSnapshotForAssignmentScope(snapshot,normalizeApplicationContextExtension({available:true,membershipStatus:'active',roles:['coach','admin'],assignmentScopeEnforced:true,assignedClientIds:['C1']}),'coach');assert.deepEqual(filtered.data.clients.map(x=>x.id),['C1']);assert.deepEqual(filtered.data.sessions.map(x=>x.id),['S1']);assert.equal(filtered.data.coachAvailability.length,1);});
test('membresía suspendida bloquea todas las aplicaciones',()=>assert.throws(()=>filterSnapshotForAssignmentScope({data:{}},{available:true,membershipStatus:'suspended'},'coach'),/ACCESS_SUSPENDED/));
test('Cliente y Coach no reciben estado Admin',()=>{assert.equal(projectAdminSnapshot(rawAdmin(),{role:'client'}).available,false);assert.equal(projectAdminSnapshot(rawAdmin(),{role:'coach'}).available,false);});
test('bootstrap Admin filtra campos secretos',()=>{const state=admin();assert.equal(state.collections.organizationUsers[0].token,undefined);assert.deepEqual(Object.keys(state.collections).sort(),[...M26_ADMIN_COLLECTION_KEYS].sort());});
test('comando sensible exige motivo',()=>assert.throws(()=>createAdminCommand({operationId:'OP1',type:'ADMIN_ROL_OTORGAR',entityId:'U2',payload:{userId:'U2',role:'coach'}},admin()),/REASON_REQUIRED/));
test('comando Admin es online only',()=>assert.equal(createAdminCommand({operationId:'OP2',type:'ADMIN_TAREA_CREAR',entityId:org,payload:{title:'Revisar'}},admin()).onlineOnly,true));
test('servicio Admin no encola sin conexión',async()=>{const service=createAdminCommandService({transport:{execute:async()=>({ok:true,kind:'ack'})},getToken:async()=>'jwt',getAdminState:admin,isOnline:()=>false});await assert.rejects(()=>service.execute({operationId:'OP3',type:'ADMIN_TAREA_CREAR',entityId:org,payload:{title:'Revisar'}}),/ONLINE_REQUIRED/);});
test('servicio Admin rehidrata después de ACK',async()=>{const order=[];const service=createAdminCommandService({transport:{execute:async()=>{order.push('ack');return {ok:true,kind:'ack'};}},getToken:async()=>'jwt',getAdminState:admin,isOnline:()=>true,refreshState:async()=>order.push('hydrate')});await service.execute({operationId:'OP4',type:'ADMIN_TAREA_CREAR',entityId:org,payload:{title:'Revisar'}});assert.deepEqual(order,['ack','hydrate']);});
test('navegación separa las tres aplicaciones sin romper contratos Cliente Coach',()=>{const client=navigationForRole('client');const coach=navigationForRole('coach');assert.equal(roleHome('admin'),'admin-inicio');assert.equal(areaAllowedForRole('hoy','admin'),false);assert.equal(areaAllowedForRole('admin-inicio','coach'),false);assert.deepEqual(client.primary.map(x=>x.key),['hoy','planificacion','sesion','progreso']);assert.equal(client.context.some(x=>x.key==='mensajes'),true);assert.deepEqual(coach.primary.map(x=>x.key),['hoy','clientes','agenda','biblioteca']);assert.equal(coach.tools.some(x=>x.key==='mensajes'),true);});

test('hidratación inicial conserva un área explícita de regresión',()=>{const previous=createProductionState({activeArea:'planificacion',selectedClientId:'C1'});const state=stateFromBootstrap({user:{id:'U-COACH',role:'coach',name:'Coach'},canary:{active:true},data:{clients:[{id:'C1',name:'Cliente'}],trainingCycles:[],sessions:[]}},previous);assert.equal(state.activeArea,'planificacion');const vm=createRouteViewModel(createShellViewModel(state),state);assert.equal(vm.kind,'planificacion');assert.ok(Array.isArray(vm.cycles));assert.ok(Array.isArray(vm.sessions));});

test('primera hidratación Admin entra en su aplicación propia',()=>{const state=stateFromBootstrap({user:{id:'U-ADMIN',role:'admin',name:'Admin'},canary:{active:true},data:{clients:[]},admin:null},createProductionState());assert.equal(state.activeArea,'admin-inicio');});
test('comunicación solo se proyecta para Cliente y Coach',()=>{const raw={ok:true,threads:[],messages:[],notifications:[],revision:1};assert.equal(projectCommunicationSnapshot(raw,{role:'admin'}).available,false);assert.equal(projectCommunicationSnapshot(raw,{role:'client'}).available,true);});
test('mensaje vacío se rechaza',()=>assert.throws(()=>createCommunicationCommand({operationId:'COM1',type:'MESSAGE_SEND',entityId:'T1',payload:{body:'  '}},createCommunicationState({available:true}),'client'),/BODY_INVALID/));
test('servicio de comunicación requiere conexión',async()=>{const service=createCommunicationService({transport:{execute:async()=>({ok:true,kind:'ack'})},getToken:async()=>'jwt',getState:()=>createCommunicationState({available:true}),getRole:()=> 'coach',isOnline:()=>false});await assert.rejects(()=>service.execute({operationId:'COM2',type:'MESSAGE_THREAD_OPEN',entityId:'C1',payload:{clientId:'C1'}}),/ONLINE_REQUIRED/);});

test('servicio Admin rechaza colisión de operationId',async()=>{let release;const gate=new Promise(r=>release=r);const service=createAdminCommandService({transport:{execute:async()=>{await gate;return {ok:true,kind:'ack'};}},getToken:async()=>'jwt',getAdminState:admin,isOnline:()=>true});const first=service.execute({operationId:'OP-COLLISION',type:'ADMIN_TAREA_CREAR',entityId:org,payload:{title:'Uno'}});await assert.rejects(()=>service.execute({operationId:'OP-COLLISION',type:'ADMIN_TAREA_CREAR',entityId:org,payload:{title:'Dos'}}),/COLLISION/);release();await first;});
test('servicio comunicación rechaza colisión de operationId',async()=>{let release;const gate=new Promise(r=>release=r);const state=createCommunicationState({available:true});const service=createCommunicationService({transport:{execute:async()=>{await gate;return {ok:true,kind:'ack'};}},getToken:async()=>'jwt',getState:()=>state,getRole:()=> 'coach',isOnline:()=>true});const first=service.execute({operationId:'COM-COLLISION',type:'MESSAGE_THREAD_OPEN',entityId:'C1',payload:{clientId:'C1',subject:'Uno'}});await assert.rejects(()=>service.execute({operationId:'COM-COLLISION',type:'MESSAGE_THREAD_OPEN',entityId:'C2',payload:{clientId:'C2',subject:'Dos'}}),/COLLISION/);release();await first;});
test('catálogos excluyen pagos',()=>{assert.equal(M26_ADMIN_COMMAND_TYPES.some(x=>/PAGO|PAYMENT|COBRO/.test(x)),false);assert.equal(M26_COMMUNICATION_COMMAND_TYPES.some(x=>/PAGO|PAYMENT|COBRO/.test(x)),false);});
