import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {M26_COMMAND_REGISTRY,M26_EXTENDED_COMMAND_REGISTRY,validatedRuntimeRegistry,createCommand,createCommandBus,createMemoryOperationRepository} from '../src/m26/index.js';
import {buildCheckinRegisterCommand,buildHabitDefineCommand,buildPrivateNoteCreateCommand,createEngagementCommandService,buildAdaptiveSessionContext,applyAdaptiveContext,generateSessionProposal,createExerciseCatalog,validateQaIdentity} from '../src/m26/index.js';
import {createProductionState,stateFromBootstrap} from '../src/m26/production-state.js';import {createShellViewModel} from '../src/m26/shell/shell-view-model.js';import {createRouteViewModel} from '../src/m26/modules/route-view-model.js';import {renderRouteView} from '../src/m26/modules/route-render.js';
const records=JSON.parse(await readFile(new URL('../baseline_m25_2/exercise-catalog-m25.json',import.meta.url),'utf8'));const catalog=createExerciseCatalog(records);const clientId='57339e70-7a99-48d6-820f-7d4a51f89d9d';const now=new Date('2026-07-19T12:00:00Z');
function state({role='client',checkins=[],appointments=[],sessionExecutions=[]}={}){return stateFromBootstrap({user:{id:role==='coach'?'coach-id':'client-id',role,clientId:role==='client'?clientId:null,name:'QA'},canary:{active:true,version:'rc11'},environment:{commandRegistry:M26_EXTENDED_COMMAND_REGISTRY},serverTime:now.toISOString(),data:{clients:[{id:clientId,name:'Cliente QA'}],checkins,appointments,sessionExecutions,iriAssessments:[],trainingCycles:[],habits:[],habitLogs:[],privateNotes:[]}},createProductionState());}
function checkin(values={}){return {id:crypto.randomUUID(),clientId,createdAt:'2026-07-19T09:00:00Z',energy:7,sleep:7,stress:3,pain:1,...values};}
function execution(id,date,rows){return {id,clientId,completedAt:date,status:'completed',results:rows};}

test('registro base conserva 44 y extensión validada suma 52 sin contaminar el default',()=>{assert.equal(M26_COMMAND_REGISTRY.length,44);assert.equal(M26_EXTENDED_COMMAND_REGISTRY.length,52);const runtime=validatedRuntimeRegistry(M26_EXTENDED_COMMAND_REGISTRY);assert.equal(runtime.ok,true);assert.equal(runtime.registry.length,52);assert.throws(()=>createCommand({type:'CHECKIN_REGISTRAR',entityType:'checkin',entityId:'x',clientId,baseRevision:0,payload:{}}),/COMMAND_NOT_REGISTERED/);assert.equal(createCommand({type:'CHECKIN_REGISTRAR',entityType:'checkin',entityId:'x',clientId,baseRevision:0,payload:{}},{registry:M26_EXTENDED_COMMAND_REGISTRY,role:'client'}).type,'CHECKIN_REGISTRAR');});

test('registro remoto con rol de cliente incorrecto se rechaza',()=>{const installed=M26_EXTENDED_COMMAND_REGISTRY.map((x)=>x.type==='CHECKIN_REGISTRAR'?{...x,allowedRoles:['admin','coach','client_wrong']}:x);const runtime=validatedRuntimeRegistry(installed);assert.equal(runtime.ok,false);assert.ok(runtime.rejected.some((x)=>x.type==='CHECKIN_REGISTRAR'&&x.field==='allowedRoles'));});

test('builders engagement producen payloads canónicos y respetan roles',()=>{const c=buildCheckinRegisterCommand({clientId,checkin:{energy:6,sleep:7,stress:4,pain:1}},{registry:M26_EXTENDED_COMMAND_REGISTRY,role:'client'});assert.equal(c.payload.patch.status,'confirmado');assert.equal(c.conflictSensitive,false);const h=buildHabitDefineCommand({clientId,habit:{title:'Caminar',target:4,unit:'días'}},{registry:M26_EXTENDED_COMMAND_REGISTRY,role:'coach'});assert.equal(h.entityType,'habit');assert.throws(()=>buildPrivateNoteCreateCommand({clientId,body:'Nota interna'},{registry:M26_EXTENDED_COMMAND_REGISTRY,role:'client'}),/ROLE_NOT_ALLOWED/);});

test('servicio encola check-in offline y bloquea nota privada fuera de línea',async()=>{const bus=createCommandBus({transport:{preflight:async()=>({}),execute:async()=>({kind:'ack'})},repository:createMemoryOperationRepository(),getToken:async()=>null,registry:M26_EXTENDED_COMMAND_REGISTRY,getRole:()=> 'client'});const service=createEngagementCommandService({commandBus:bus,installedRegistry:M26_EXTENDED_COMMAND_REGISTRY,getRole:()=> 'client',isOnline:()=>false});const result=await service.registerCheckin({clientId,checkin:{energy:6,sleep:7,stress:4,pain:1}});assert.equal(result.queued,true);await assert.rejects(()=>service.createPrivateNote({clientId,body:'Privada'}),/ROLE_FORBIDDEN|ONLINE_REQUIRED/);});

test('nota privada Coach solo queda confirmada después de ACK',async()=>{let sent=null;const bus=createCommandBus({transport:{preflight:async()=>({}),execute:async(_t,c)=>{sent=c;return {kind:'ack',remoteRevision:1};}},repository:createMemoryOperationRepository(),getToken:async()=> 'qa-token',registry:M26_EXTENDED_COMMAND_REGISTRY,getRole:()=> 'coach'});const service=createEngagementCommandService({commandBus:bus,installedRegistry:M26_EXTENDED_COMMAND_REGISTRY,getRole:()=> 'coach',isOnline:()=>true});const result=await service.createPrivateNote({clientId,body:'Observación solo para el Coach'});assert.equal(result.ok,true);assert.equal(sent.type,'NOTA_PRIVADA_CREAR');assert.equal(sent.payload.patch.visibility,'coach_only');});

test('dolor alto detiene generación automática y exige revisión Coach',()=>{const s=state({checkins:[checkin({pain:8})]});const context=buildAdaptiveSessionContext(s,clientId,{now});assert.equal(context.decision.level,'hold');const input=applyAdaptiveContext({clientId,goal:'fuerza',durationMinutes:50,experience:'intermedio',modality:'híbrido',ageYears:35,equipment:['mancuernas']},s,clientId,{now});assert.throws(()=>generateSessionProposal(input,catalog),/SAFETY_REVIEW_REQUIRED/);});

test('recuperación limitada reduce volumen, RPE y evita circuitos',()=>{const s=state({checkins:[checkin({sleep:3,energy:4,stress:8,pain:3})]});const input=applyAdaptiveContext({clientId,goal:'fuerza',durationMinutes:50,experience:'intermedio',modality:'híbrido',ageYears:35,equipment:['mancuernas','sin equipo']},s,clientId,{now});const proposal=generateSessionProposal(input,catalog);assert.equal(proposal.rationale.adaptiveLevel,'reduced');assert.equal(proposal.exercises.length,5);assert.ok(proposal.exercises.every((x)=>x.sets===2&&x.targetRpe===6&&x.restSeconds>=60));assert.equal(proposal.structure.type,'series');assert.equal(proposal.requiresManualReview,true);});

test('adherencia baja simplifica la sesión a cuatro patrones',()=>{const appointments=[1,2,3,4].map((i)=>({id:`a${i}`,clientId,startAt:`2026-07-0${i}T10:00:00Z`,status:'confirmado'}));const s=state({checkins:[checkin()],appointments,sessionExecutions:[execution('e1','2026-07-01T11:00:00Z',[])]});const context=buildAdaptiveSessionContext(s,clientId,{now});assert.equal(context.decision.level,'simplified');const proposal=generateSessionProposal(applyAdaptiveContext({clientId,goal:'salud',durationMinutes:45,experience:'inicial',modality:'online',ageYears:40,equipment:[]},s,clientId,{now}),catalog);assert.equal(proposal.exercises.length,4);});

test('progresión estable solo propone un rango y mantiene decisión del Coach',()=>{const ex=catalog.list().find((x)=>String(x.pattern).toLowerCase().includes('sentadilla'))||catalog.list()[0];const proposal=generateSessionProposal({clientId,goal:'fuerza',durationMinutes:40,experience:'intermedio',modality:'presencial',ageYears:35,equipment:[ex.equipment],patterns:[ex.pattern],preferredExerciseIds:[ex.id],previousLoads:{[ex.id]:20},adaptiveContext:{decision:{level:'normal',progressionAllowed:true,patternLimit:6,durationFactor:1},evidence:{adherence:1}}},catalog);assert.match(proposal.exercises[0].loadInstruction,/el entrenador decide/);assert.equal(proposal.qualityChecks.automaticProgression,false);});

test('actividad Coach habilita hábitos con registro extendido y Cliente no ve formulario Coach',()=>{const coach=state({role:'coach'});coach.selectedClientId=clientId;coach.activeArea='actividad';let html=renderRouteView(createRouteViewModel(createShellViewModel(coach),coach,now));assert.match(html,/data-engagement-form="habit-definition"/);assert.match(html,/data-engagement-action="define-habit">Publicar hábito/);const client=state({role:'client'});client.activeArea='actividad';html=renderRouteView(createRouteViewModel(createShellViewModel(client),client,now));assert.doesNotMatch(html,/data-engagement-form="habit-definition"/);assert.doesNotMatch(html,/onclick=/i);});

test('QA normaliza role client a contrato cliente sin ampliar permisos',()=>{const result=validateQaIdentity({session:{token:'t',user:{id:'u',email:'iberfit.cl+qa.m26@gmail.com'}},bootstrap:{role:'client'},expectedRole:'cliente'});assert.equal(result.ok,true);assert.equal(result.role,'cliente');});
