const toast=(message)=>{try{globalThis.dispatchEvent(new CustomEvent('m26:toast',{detail:{message}}));}catch{}};
const text=(data,key,max=4000)=>String(data.get(key)||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);
const rev=(data)=>{const n=Number(data.get('baseRevision')||0);return Number.isInteger(n)&&n>=0?n:0;};
function json(value){const raw=String(value||'').trim();if(!raw)return {};const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('M26_ADMIN_CONFIGURATION_JSON_INVALID');return parsed;}
export function createAdminController({root,store,service,render=()=>{}}={}){if(!root?.addEventListener||!store?.getState)throw new Error('M26_ADMIN_CONTROLLER_CONTEXT_REQUIRED');let busy=false;async function execute(input,success){if(busy)return false;busy=true;try{await service.execute(input);toast(success);render();return true;}catch(error){toast(/ONLINE_REQUIRED/.test(String(error?.message||error))?'Esta operación administrativa requiere conexión.':'No fue posible confirmar el cambio.');throw error;}finally{busy=false;}}
  async function onSubmit(event){const form=event.target.closest?.('[data-admin-form]');if(!form)return;event.preventDefault();const kind=form.dataset.adminForm;const data=new FormData(form);const org=store.getState().admin?.organization?.id;
    if(kind==='user-status')await execute({type:'ADMIN_USUARIO_CAMBIAR_ESTADO',entityId:text(data,'userId',200),organizationId:org,baseRevision:rev(data),reason:text(data,'reason',500),payload:{userId:text(data,'userId',200),status:text(data,'status',40)}},'Estado actualizado.');
    else if(kind==='role-change'){const action=text(data,'action',20);await execute({type:action==='revoke'?'ADMIN_ROL_REVOCAR':'ADMIN_ROL_OTORGAR',entityId:text(data,'userId',200),organizationId:org,reason:text(data,'reason',500),payload:{userId:text(data,'userId',200),role:text(data,'role',30)}},action==='revoke'?'Aplicación revocada.':'Aplicación autorizada.');}
    else if(kind==='assignment-create')await execute({type:'ADMIN_ASIGNACION_CREAR',entityId:org,organizationId:org,reason:text(data,'reason',500),payload:{coachUserId:text(data,'coachUserId',200),clientId:text(data,'clientId',200),startsAt:text(data,'startsAt',40)}},'Asignación creada.');
    else if(kind==='assignment-end')await execute({type:'ADMIN_ASIGNACION_FINALIZAR',entityId:text(data,'assignmentId',200),organizationId:org,baseRevision:rev(data),reason:text(data,'reason',500),payload:{assignmentId:text(data,'assignmentId',200)}},'Asignación finalizada.');
    else if(kind==='lead-create')await execute({type:'ADMIN_LEAD_CREAR',entityId:org,organizationId:org,payload:{name:text(data,'name',200),email:text(data,'email',254),phone:text(data,'phone',80),source:text(data,'source',120),objective:text(data,'objective',1000)}},'Lead registrado.');
    else if(kind==='lead-update')await execute({type:'ADMIN_LEAD_ACTUALIZAR',entityId:text(data,'leadId',200),organizationId:org,baseRevision:rev(data),reason:text(data,'reason',500),payload:{leadId:text(data,'leadId',200),status:text(data,'status',40),nextActionAt:text(data,'nextActionAt',80)}},'Lead actualizado.');
    else if(kind==='client-lifecycle')await execute({type:'ADMIN_CLIENTE_CAMBIAR_CICLO',entityId:text(data,'clientId',200),organizationId:org,reason:text(data,'reason',500),payload:{clientId:text(data,'clientId',200),status:text(data,'status',40)}},'Ciclo actualizado.');
    else if(kind==='task-create')await execute({type:'ADMIN_TAREA_CREAR',entityId:org,organizationId:org,payload:{priority:text(data,'priority',30),taskType:text(data,'taskType',80),title:text(data,'title',200),detail:text(data,'detail',2000)}},'Tarea creada.');
    else if(kind==='task-resolve')await execute({type:'ADMIN_TAREA_RESOLVER',entityId:text(data,'taskId',200),organizationId:org,baseRevision:rev(data),reason:text(data,'reason',500),payload:{taskId:text(data,'taskId',200)}},'Tarea resuelta.');
    else if(kind==='template-save'){const key=text(data,'key',80);await execute({type:'ADMIN_PLANTILLA_GUARDAR',entityId:key,organizationId:org,payload:{key,name:text(data,'name',160),channel:text(data,'channel',30),subject:text(data,'subject',200),body:text(data,'body',4000)}},'Plantilla guardada.');}
    else if(kind==='automation-save'){const key=text(data,'key',80);await execute({type:'ADMIN_AUTOMATIZACION_GUARDAR',entityId:key,organizationId:org,payload:{key,name:text(data,'name',160),triggerType:text(data,'triggerType',80),actionType:text(data,'actionType',80),status:text(data,'status',30),configuration:json(data.get('configuration'))}},'Automatización guardada.');}
    else if(kind==='settings-save')await execute({type:'ADMIN_ORGANIZACION_ACTUALIZAR',entityId:text(data,'organizationId',200)||org,organizationId:org,baseRevision:rev(data),reason:text(data,'reason',500),payload:{name:text(data,'name',200),timezone:text(data,'timezone',100),locale:text(data,'locale',30)}},'Configuración actualizada.');
  }
  return Object.freeze({mount(){root.addEventListener('submit',onSubmit);},destroy(){root.removeEventListener('submit',onSubmit);}});
}
