const e=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const badge=(v)=>`<span class="m26-admin-badge">${e(v||'Sin estado')}</span>`;
const empty=(t,c)=>`<section class="m26-admin-empty"><h3>${e(t)}</h3><p>${e(c)}</p></section>`;
const stat=(t,v)=>`<article class="m26-admin-stat"><span>${e(t)}</span><strong>${e(v)}</strong></article>`;
const intro=(k,t,c)=>`<section class="m26-admin-hero"><p class="m26-eyebrow">${e(k)}</p><h2>${e(t)}</h2><p>${e(c)}</p></section>`;
const rows=(headers,items)=>`<div class="m26-admin-table"><table><thead><tr>${headers.map((h)=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${items.join('')}</tbody></table></div>`;
function form(kind,fields,button){return `<form data-admin-form="${kind}" class="m26-admin-form">${fields}<button type="submit">${e(button)}</button></form>`;}
function commandPriority(item){
  const action=item?.action||{};
  return `<article class="m26-admin-priority is-${e(item.kind||'process')}"><div><p class="m26-eyebrow">${e(item.stageLabel||'Seguimiento')}</p><h3>${e(item.clientName||'Cliente')}</h3><p>${e(action.reason||'Revisión pendiente')}</p><small>${e(item.coachNames?.length?`Coach: ${item.coachNames.join(', ')}`:'Sin Coach asignado')}</small></div><button type="button" data-m26-area="${e(action.area||'admin-clientes')}">${e(action.label||'Revisar')}</button></article>`;
}
function coachLoadCard(item){
  const value=item.loadPercent==null?'Sin capacidad definida':`${item.loadPercent}%`;
  const detail=item.capacityHours==null?`${item.clientCount} clientes`:`${item.assignedHours} de ${item.capacityHours} h · ${item.clientCount} clientes`;
  return `<article class="m26-admin-coach-load is-${e(item.status||'unknown')}"><div><strong>${e(item.coachName)}</strong><small>${e(detail)}</small></div><span>${e(value)}</span></article>`;
}
function renderHome(vm){
  const cc=vm.commandCenter||{summary:{},priorities:[],coachLoad:[],criticalTasks:[]};
  const s=cc.summary||{};
  const priorities=cc.priorities?.length?cc.priorities.slice(0,8).map(commandPriority).join(''):empty('Servicio al día','No hay recorridos de cliente que requieran una decisión administrativa.');
  const loads=cc.coachLoad?.length?cc.coachLoad.map(coachLoadCard).join(''):empty('Sin carga registrada','La capacidad del equipo aparecerá aquí cuando exista información.');
  return `<div class="m26-admin-route">
    ${intro('Dirección del servicio','IBERFIT Command Center','Una única vista para decidir qué necesita atención en clientes, equipo y operación.')}
    <section class="m26-admin-stats">
      ${stat('Clientes',s.totalClients??vm.summary.activeClients??0)}
      ${stat('Sin Coach',s.unassignedClients??0)}
      ${stat('IRI pendientes',s.iriPending??0)}
      ${stat('Planificaciones',s.planningPending??0)}
      ${stat('Sin próxima cita',s.schedulingPending??0)}
      ${stat('Coaches ≥85%',s.coachesNearCapacity??0)}
    </section>
    <section class="m26-admin-panel m26-admin-command">
      <div class="m26-admin-section-heading"><div><p class="m26-eyebrow">Decisiones</p><h3>Qué requiere atención ahora</h3><p>Priorizado por asignación y etapa del recorrido IBERFIT.</p></div>${badge(cc.priorities?.length?`${cc.priorities.length} por revisar`:'Al día')}</div>
      <div class="m26-admin-priority-list">${priorities}</div>
    </section>
    <section class="m26-admin-grid">
      <article class="m26-admin-panel"><div class="m26-admin-section-heading"><div><p class="m26-eyebrow">Equipo</p><h3>Capacidad de Coaches</h3></div></div><div class="m26-admin-load-list">${loads}</div></article>
      <article class="m26-admin-panel"><div class="m26-admin-section-heading"><div><p class="m26-eyebrow">Operación</p><h3>Tareas abiertas</h3></div>${badge(s.criticalTasks?`${s.criticalTasks} prioritarias`:`${s.openTasks||0} abiertas`)}</div>${vm.tasks.length?vm.tasks.map((x)=>`<div class="m26-admin-list-item"><div><strong>${e(x.title||x.type)}</strong><small>${e(x.detail||'')}</small></div>${badge(x.status)}</div>`).join(''):empty('Sin tareas','No hay incidencias abiertas.')}</article>
    </section>
    <section class="m26-admin-panel"><div class="m26-admin-section-heading"><div><p class="m26-eyebrow">Trazabilidad</p><h3>Actividad administrativa reciente</h3></div></div>${vm.audit.length?vm.audit.slice(0,8).map((x)=>`<div class="m26-admin-list-item"><strong>${e(x.summary||x.eventType)}</strong><small>${e(x.occurredAt||'')}</small></div>`).join(''):empty('Sin eventos','Todavía no hay actividad administrativa.')}</section>
  </div>`;
}
function renderUsers(vm){const cards=vm.users.map((u)=>`<article class="m26-admin-panel"><h3>${e(u.name||u.email||'Usuario')}</h3><p>${e(u.email||'')}</p>${badge(u.status)}<p>${e((u.roles||[]).join(', ')||u.primaryRole||'Sin rol')}</p>${vm.canManageStatus?form('user-status',`<input type="hidden" name="userId" value="${e(u.userId||u.id)}"><input type="hidden" name="baseRevision" value="${e(u.revision||0)}"><select name="status"><option value="active">Activo</option><option value="suspended">Suspendido</option><option value="inactive">Inactivo</option></select><textarea name="reason" minlength="3" required placeholder="Motivo"></textarea>`,'Guardar estado'):''}${vm.canManageRoles?form('role-change',`<input type="hidden" name="userId" value="${e(u.userId||u.id)}"><select name="action"><option value="grant">Otorgar</option><option value="revoke">Revocar</option></select><select name="role"><option value="client">Cliente</option><option value="coach">Coach</option><option value="admin">Admin</option></select><textarea name="reason" minlength="3" required placeholder="Motivo"></textarea>`,'Cambiar acceso'):''}</article>`).join('');return `<div class="m26-admin-route">${intro('Identidad','Usuarios y accesos','Administra estados y aplicaciones autorizadas sin autoelevar permisos.')}<section class="m26-admin-cards">${cards||empty('Sin usuarios','No hay usuarios visibles.')}</section></div>`;}
function renderTeam(vm){
  const assign=vm.canManage?form('assignment-create',`<select name="coachUserId" required><option value="">Coach</option>${vm.coaches.map((x)=>`<option value="${e(x.userId||x.id)}">${e(x.name||x.email)}</option>`).join('')}</select><select name="clientId" required><option value="">Cliente</option>${vm.clients.map((x)=>`<option value="${e(x.id)}">${e(x.name)}</option>`).join('')}</select><input type="date" name="startsAt" required><textarea name="reason" minlength="3" required placeholder="Motivo"></textarea>`,'Crear asignación'):'';
  const table=rows(['Coach','Cliente','Estado','Acción'],vm.assignments.map((a)=>`<tr><td>${e(a.coachName||'Coach')}</td><td>${e(a.clientName||'Cliente')}</td><td>${badge(a.status)}</td><td>${a.status==='active'&&vm.canManage?form('assignment-end',`<input type="hidden" name="assignmentId" value="${e(a.id)}"><input type="hidden" name="baseRevision" value="${e(a.revision||0)}"><input name="reason" minlength="3" required placeholder="Motivo">`,'Finalizar'):'—'}</td></tr>`));
  return `<div class="m26-admin-route">${intro('Equipo','Coaches y asignaciones','Controla quién acompaña a cada cliente y protege la continuidad del servicio.')}${assign}<section class="m26-admin-panel">${vm.assignments.length?table:empty('Sin asignaciones','No hay relaciones Coach–Cliente registradas.')}</section></div>`;
}
function clientDelete(c){
  const expected=String(c.email||c.name||'').trim();
  const identity=c.email?`Correo: ${c.email}`:`Nombre: ${c.name}`;
  return `<details class="m26-admin-danger"><summary>Eliminar cliente</summary><div class="m26-admin-danger-body"><p class="m26-eyebrow">Zona crítica</p><h4>Eliminar ${e(c.name)} de forma permanente</h4><p>Esta acción elimina el expediente operativo asociado y no se puede deshacer. Si existen registros legales, fiscales o de gobierno protegidos, IBERFIT bloqueará la operación y no borrará nada.</p><dl><div><dt>Cliente</dt><dd>${e(c.name)}</dd></div><div><dt>${c.email?'Correo':'Identificador'}</dt><dd>${e(c.email||c.id)}</dd></div><div><dt>ID</dt><dd>${e(c.id)}</dd></div></dl>${form('client-delete',`<input type="hidden" name="clientId" value="${e(c.id)}"><label class="m26-admin-danger-check"><input type="checkbox" name="confirmAcknowledged" value="yes" required><span>Entiendo que la eliminación es permanente y que la identidad de acceso puede conservarse por seguridad.</span></label><label>Confirma ${e(identity)}<input name="confirmValue" required autocomplete="off" placeholder="${e(expected)}"></label><label>Escribe ELIMINAR<input name="confirmPhrase" required autocomplete="off" pattern="ELIMINAR" placeholder="ELIMINAR"></label><label>Motivo<textarea name="reason" minlength="8" maxlength="500" required placeholder="Motivo de la eliminación"></textarea></label>`,'Eliminar definitivamente')}</div></details>`;
}
function renderClients(vm){
  const lead=vm.canManage?form('lead-create',`<input name="name" maxlength="200" required placeholder="Nombre"><input type="email" name="email" maxlength="254" placeholder="Correo"><input name="phone" maxlength="80" placeholder="Teléfono"><input name="source" maxlength="120" placeholder="Origen"><textarea name="objective" maxlength="1000" placeholder="Objetivo"></textarea>`,'Registrar lead'):'';
  const leadTable=rows(['Lead','Origen','Estado','Gestión'],vm.leads.map((l)=>`<tr><td><strong>${e(l.name)}</strong><small>${e(l.email||l.phone||'')}</small></td><td>${e(l.source||'')}</td><td>${badge(l.status)}</td><td>${vm.canManage?form('lead-update',`<input type="hidden" name="leadId" value="${e(l.id)}"><input type="hidden" name="baseRevision" value="${e(l.revision||0)}"><select name="status"><option value="new">Nuevo</option><option value="contacted">Contactado</option><option value="qualified">Cualificado</option><option value="evaluation">Evaluación</option><option value="won">Ganado</option><option value="lost">Perdido</option></select><input type="datetime-local" name="nextActionAt"><input name="reason" minlength="3" required placeholder="Motivo">`,'Actualizar'):'—'}</td></tr>`));
  const clients=rows(['Cliente','Ciclo','Coach','Gestión'],vm.clients.map((c)=>`<tr><td><strong>${e(c.name)}</strong><small>${e(c.email||c.id)}</small></td><td>${badge(c.lifecycle?.status||c.status)}</td><td>${e(c.coachNames?.join(', ')||'Sin coach')}</td><td>${vm.canManage?`${form('client-lifecycle',`<input type="hidden" name="clientId" value="${e(c.id)}"><select name="status"><option value="onboarding">Onboarding</option><option value="active">Activo</option><option value="paused">Pausa</option><option value="inactive">Baja</option><option value="reactivation">Reactivación</option></select><input name="reason" minlength="3" required placeholder="Motivo">`,'Actualizar')}${clientDelete(c)}`:'—'}</td></tr>`));
  const dangerStyle=`<style>.m26-admin-danger{margin-top:.7rem;border:1px solid color-mix(in srgb,#9f2d2d 40%,transparent);border-radius:14px;background:color-mix(in srgb,#9f2d2d 6%,transparent);overflow:hidden}.m26-admin-danger>summary{cursor:pointer;padding:.7rem .85rem;font-weight:700;color:#8f2424;list-style:none}.m26-admin-danger>summary::-webkit-details-marker{display:none}.m26-admin-danger-body{padding:.1rem .85rem .85rem;display:grid;gap:.65rem}.m26-admin-danger-body h4,.m26-admin-danger-body p{margin:0}.m26-admin-danger-body dl{display:grid;gap:.35rem;margin:.2rem 0}.m26-admin-danger-body dl div{display:grid;grid-template-columns:minmax(72px,.4fr) 1fr;gap:.5rem}.m26-admin-danger-body dt{font-weight:700}.m26-admin-danger-body dd{margin:0;overflow-wrap:anywhere}.m26-admin-danger-body .m26-admin-form{display:grid;gap:.55rem}.m26-admin-danger-body label{display:grid;gap:.28rem;font-size:.9rem}.m26-admin-danger-check{grid-template-columns:auto 1fr!important;align-items:start}.m26-admin-danger-body button[type=submit]{background:#9f2d2d!important;border-color:#9f2d2d!important;color:#fff!important}</style>`;
  return `<div class="m26-admin-route">${dangerStyle}${intro('Servicio','Personas y clientes','Acompaña el recorrido desde el primer contacto hasta la reactivación.')}${lead}<section class="m26-admin-panel"><h3>Leads</h3>${vm.leads.length?leadTable:empty('Sin leads','Los contactos aparecerán aquí.')}</section><section class="m26-admin-panel"><h3>Clientes</h3>${vm.clients.length?clients:empty('Sin clientes','No hay expedientes visibles.')}</section></div>`;
}
function renderSimple(vm){if(vm.kind==='admin-agenda')return `<div class="m26-admin-route">${intro('Capacidad','Agenda global','Supervisa todas las citas y modalidades.')}<section class="m26-admin-panel">${vm.appointments.length?rows(['Fecha','Cliente','Estado'],vm.appointments.map((x)=>`<tr><td>${e(x.startAt||x.start_at||x.date||'')}</td><td>${e(x.clientId||x.client_id||'')}</td><td>${badge(x.status)}</td></tr>`)):empty('Agenda vacía','No hay citas visibles.')}</section></div>`;
  if(vm.kind==='admin-operaciones'){const create=vm.canManage?form('task-create',`<select name="priority"><option value="normal">Normal</option><option value="high">Alta</option><option value="critical">Crítica</option></select><input name="taskType" value="manual_review"><input name="title" required placeholder="Título"><textarea name="detail" placeholder="Detalle"></textarea>`,'Crear tarea'):'';return `<div class="m26-admin-route">${intro('Control','Centro operativo','Centraliza incidencias y excepciones.')}${create}<section class="m26-admin-panel">${vm.tasks.length?vm.tasks.map((x)=>`<div class="m26-admin-list-item"><div><strong>${e(x.title||x.type)}</strong><p>${e(x.detail||'')}</p></div>${badge(x.status)}${vm.canManage&&!['resolved','cancelled'].includes(x.status)?form('task-resolve',`<input type="hidden" name="taskId" value="${e(x.id)}"><input type="hidden" name="baseRevision" value="${e(x.revision||0)}"><input name="reason" minlength="3" required placeholder="Resolución">`,'Resolver'):''}</div>`).join(''):empty('Sin tareas','No hay incidencias abiertas.')}</section></div>`;}
  if(vm.kind==='admin-comunicacion'){const create=vm.canManage?form('template-save',`<input name="key" pattern="[a-z0-9_.:-]{3,80}" required placeholder="Clave"><input name="name" required placeholder="Nombre"><select name="channel"><option value="in_app">In-app</option><option value="email">Email</option><option value="push">Push</option></select><input name="subject" placeholder="Asunto"><textarea name="body" required placeholder="Contenido"></textarea>`,'Guardar plantilla'):'';return `<div class="m26-admin-route">${intro('Relación','Comunicación','Gestiona plantillas y revisa entregas.')}${create}<section class="m26-admin-panel">${vm.templates.length?vm.templates.map((x)=>`<div class="m26-admin-list-item"><strong>${e(x.name||x.key)}</strong>${badge(x.status)}</div>`).join(''):empty('Sin plantillas','Crea la primera plantilla.')}</section></div>`;}
  if(vm.kind==='admin-automatizaciones'){const create=vm.canManage?form('automation-save',`<input name="key" pattern="[a-z0-9_.:-]{3,80}" required placeholder="Clave"><input name="name" required placeholder="Nombre"><select name="triggerType"><option value="appointment_window_open">Cita</option><option value="client_inactive">Inactividad</option><option value="checkin_due">Check-in</option><option value="iri_review_due">Revisión IRI</option></select><select name="actionType"><option value="notification">Notificación</option><option value="operational_task">Tarea</option></select><select name="status"><option value="draft">Borrador</option><option value="active">Activa</option><option value="paused">Pausada</option></select><textarea name="configuration" placeholder='{"templateKey":"appointment.reminder"}'></textarea>`,'Guardar regla'):'';return `<div class="m26-admin-route">${intro('Eficiencia','Automatizaciones','Automatiza tareas, nunca decisiones profesionales.')}${create}<section class="m26-admin-panel">${vm.rules.length?vm.rules.map((x)=>`<div class="m26-admin-list-item"><strong>${e(x.name||x.key)}</strong>${badge(x.status)}</div>`).join(''):empty('Sin reglas','No hay automatizaciones.')}</section></div>`;}
  if(vm.kind==='admin-analitica')return `<div class="m26-admin-route">${intro('Decisiones','Analítica del servicio','Datos operativos sin inventar métricas ausentes.')}<section class="m26-admin-stats">${stat('Clientes activos',vm.analytics?.activeClients??'Sin datos')}${stat('Adherencia',vm.analytics?.averageAdherence??'Sin datos')}${stat('Bajas 30 días',vm.analytics?.churn30d??'Sin datos')}${stat('Conversión',vm.analytics?.conversionRate??'Sin datos')}</section></div>`;
  if(vm.kind==='admin-auditoria')return `<div class="m26-admin-route">${intro('Seguridad','Auditoría','Historial minimizado e inmutable.')}<section class="m26-admin-panel">${vm.events.length?rows(['Fecha','Evento','Actor','Resumen'],vm.events.map((x)=>`<tr><td>${e(x.occurredAt||'')}</td><td>${e(x.eventType||'')}</td><td>${e(x.actorUserId||'')}</td><td>${e(x.summary||'')}</td></tr>`)):empty('Sin eventos','No hay auditoría visible.')}</section></div>`;
  const org=vm.organization||{};return `<div class="m26-admin-route">${intro('Sistema','Configuración de IBERFIT','Parámetros comunes de las tres aplicaciones.')}<section class="m26-admin-stats">${stat('Organización',org.name||'IBERFIT')}${stat('Zona horaria',org.timezone||'America/Santiago')}${stat('Idioma',org.locale||'es-CL')}</section>${vm.canManage?form('settings-save',`<input type="hidden" name="organizationId" value="${e(org.id)}"><input type="hidden" name="baseRevision" value="${e(org.revision||0)}"><input name="name" value="${e(org.name||'IBERFIT')}" required><input name="timezone" value="${e(org.timezone||'America/Santiago')}" required><input name="locale" value="${e(org.locale||'es-CL')}" required><textarea name="reason" minlength="3" required placeholder="Motivo"></textarea>`,'Guardar configuración'):''}<section class="m26-admin-notice"><strong>Pagos no incluidos</strong><p>Se implementarán al final y únicamente en Admin.</p></section></div>`;}
export function renderAdminRoute(vm){if(!vm?.admin)return null;if(vm.kind==='admin-unavailable')return `<div class="m26-admin-route">${intro('Aplicación Admin','Administración no disponible','El backend RC40 no está instalado o no respondió. Cliente y Coach continúan funcionando.')}</div>`;if(vm.kind==='admin-forbidden')return `<div class="m26-admin-route">${intro('Acceso protegido','Permiso insuficiente','La interfaz no puede conceder capacidades.')}</div>`;if(vm.kind==='admin-inicio')return renderHome(vm);if(vm.kind==='admin-usuarios')return renderUsers(vm);if(vm.kind==='admin-equipo')return renderTeam(vm);if(vm.kind==='admin-clientes')return renderClients(vm);return renderSimple(vm);}
