import {adminCan,ADMIN_CAPABILITIES,routeAllowedForAdmin} from './permission-policy.js';
import {adminCollection} from './admin-state.js';
const clone=(v)=>v==null?v:structuredClone(v);
function clientRows(state){const life=new Map(adminCollection(state,'clientLifecycle').map((x)=>[String(x.clientId),x]));const assignments=new Map();for(const x of adminCollection(state,'coachClientAssignments')){if(x.status!=='active')continue;const a=assignments.get(String(x.clientId))||[];a.push(x);assignments.set(String(x.clientId),a);}return Object.freeze((state.collections?.clients||[]).map((x)=>Object.freeze({id:String(x.id||''),name:String(x.name||x.nombre||'Cliente'),status:String(x.status||''),modality:String(x.modality||x.modalidad||''),lifecycle:clone(life.get(String(x.id))||null),assignments:Object.freeze(clone(assignments.get(String(x.id))||[]))})));}
export function augmentAdminShellViewModel(vm,state){if(vm?.mode!=='authenticated'||vm?.identity?.role!=='admin')return vm;return Object.freeze({...vm,selectedClient:null,clientOptions:Object.freeze([]),canChangeClient:false,admin:Object.freeze({available:state?.admin?.available===true,reason:state?.admin?.reason||null,organization:clone(state?.admin?.organization||null),summary:clone(state?.admin?.summary||{})})});}
export function createAdminRouteViewModel(base,shellVm,state){const role=String(shellVm?.identity?.role||state?.identity?.role||'');const area=String(shellVm?.activeArea||state?.activeArea||'');if(role!=='admin'||!area.startsWith('admin-'))return base;if(state?.admin?.available!==true)return Object.freeze({...base,admin:true,kind:'admin-unavailable',reason:state?.admin?.reason||'backend_unavailable'});if(!routeAllowedForAdmin(state.admin,area))return Object.freeze({...base,admin:true,kind:'admin-forbidden'});const common={...base,admin:true,area,organization:clone(state.admin.organization),summary:clone(state.admin.summary),analytics:clone(state.admin.analytics)};
  if(area==='admin-inicio')return Object.freeze({...common,kind:'admin-inicio',tasks:Object.freeze(clone(adminCollection(state,'operationalTasks').slice(0,12))),audit:Object.freeze(clone(adminCollection(state,'auditEvents').slice(0,12)))});
  if(area==='admin-usuarios')return Object.freeze({...common,kind:'admin-usuarios',users:Object.freeze(clone(adminCollection(state,'organizationUsers'))),roles:Object.freeze(clone(adminCollection(state,'applicationRoles'))),canManageStatus:adminCan(state.admin,ADMIN_CAPABILITIES.USER_MANAGE_STATUS),canManageRoles:adminCan(state.admin,ADMIN_CAPABILITIES.ROLE_MANAGE)});
  if(area==='admin-equipo')return Object.freeze({...common,kind:'admin-equipo',coaches:Object.freeze(clone(adminCollection(state,'coachProfiles'))),assignments:Object.freeze(clone(adminCollection(state,'coachClientAssignments'))),clients:clientRows(state),canManage:adminCan(state.admin,ADMIN_CAPABILITIES.ASSIGNMENT_MANAGE)});
  if(area==='admin-clientes')return Object.freeze({...common,kind:'admin-clientes',leads:Object.freeze(clone(adminCollection(state,'leads'))),clients:clientRows(state),canManage:adminCan(state.admin,ADMIN_CAPABILITIES.CLIENT_LIFECYCLE_MANAGE)});
  if(area==='admin-agenda')return Object.freeze({...common,kind:'admin-agenda',appointments:Object.freeze(clone(state.collections?.appointments||[])),coaches:Object.freeze(clone(adminCollection(state,'coachProfiles')))});
  if(area==='admin-operaciones')return Object.freeze({...common,kind:'admin-operaciones',tasks:Object.freeze(clone(adminCollection(state,'operationalTasks'))),canManage:adminCan(state.admin,ADMIN_CAPABILITIES.OPERATION_MANAGE)});
  if(area==='admin-comunicacion')return Object.freeze({...common,kind:'admin-comunicacion',templates:Object.freeze(clone(adminCollection(state,'notificationTemplates'))),deliveries:Object.freeze(clone(adminCollection(state,'notificationDeliveries'))),canManage:adminCan(state.admin,ADMIN_CAPABILITIES.MESSAGE_MANAGE_TEMPLATES)});
  if(area==='admin-automatizaciones')return Object.freeze({...common,kind:'admin-automatizaciones',rules:Object.freeze(clone(adminCollection(state,'automationRules'))),canManage:adminCan(state.admin,ADMIN_CAPABILITIES.AUTOMATION_MANAGE)});
  if(area==='admin-analitica')return Object.freeze({...common,kind:'admin-analitica',clients:clientRows(state),appointments:Object.freeze(clone(state.collections?.appointments||[]))});
  if(area==='admin-auditoria')return Object.freeze({...common,kind:'admin-auditoria',events:Object.freeze(clone(adminCollection(state,'auditEvents')))});
  if(area==='admin-configuracion')return Object.freeze({...common,kind:'admin-configuracion',canManage:adminCan(state.admin,ADMIN_CAPABILITIES.ORGANIZATION_SETTINGS_MANAGE)});
  return Object.freeze({...common,kind:'admin-forbidden'});
}
