import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {dirname} from 'node:path';

const read=(p)=>readFile(p,'utf8');
const write=async(p,s)=>{await mkdir(dirname(p),{recursive:true});await writeFile(p,s,'utf8');};
const replaceOnce=(s,old,next,label)=>{const first=s.indexOf(old);if(first<0||s.indexOf(old,first+old.length)>=0)throw new Error(`${label}: expected exactly one match`);return s.slice(0,first)+next+s.slice(first+old.length);};
const extractTemplate=(s,name)=>{const marker=`const ${name}=\``;const a=s.indexOf(marker);if(a<0)throw new Error(`missing ${name}`);const start=a+marker.length;const end=s.indexOf('`;',start);if(end<0)throw new Error(`unterminated ${name}`);return s.slice(start,end).trim()+'\n';};
const extractBetween=(s,startMarker,endMarker,label)=>{const a=s.indexOf(startMarker);if(a<0)throw new Error(`missing ${label} start`);const start=a+startMarker.length;const end=s.indexOf(endMarker,start);if(end<0)throw new Error(`missing ${label} end`);return s.slice(start,end);};
const replaceFunction=(s,signature,next,label)=>{const idx=s.indexOf(signature);if(idx<0)throw new Error(`missing ${label}`);const brace=s.indexOf('{',idx);let depth=0,end=-1;for(let i=brace;i<s.length;i++){if(s[i]==='{')depth++;else if(s[i]==='}'&&--depth===0){end=i+1;break;}}if(end<0)throw new Error(`unterminated ${label}`);return s.slice(0,idx)+next+s.slice(end);};
const forbidden=[/<style(?:\s|>)/i,/<[^>\n]*\sstyle\s*=/i,/\.style(?:\s*=|\s*\.|\s*\[)/,/\.setAttribute\(\s*['"]style['"]/,/createElement\(\s*['"]style['"]\s*\)/,/\.insertRule\s*\(/,/\bnew\s+CSSStyleSheet\s*\(/,/\.adoptedStyleSheets\s*=/];
async function scanClean(){
  const paths=(await read('tests/m26_csp_strict_first_party.test.mjs')).includes('first-party runtime remains compatible');if(!paths)return false;
  const files=['src/m26/admin/route-render.js','src/m26/app/workflow-controller-base.js','src/m26/app/workflow-controller.js','src/m26/communication/view-model.js','src/m26/modules/route-render-base.js','src/m26/modules/route-render.js','src/m26/onboarding/client-contextual-guide.js','src/m26/onboarding/client-guided-welcome.js','src/m26/onboarding/guided-tour.js','src/m26/rc39/shell-enhancer.js','src/m26/shell/shell-render.js','src/m26/ui/client-360.js','src/m26/ui/exercise-history-window.js','src/m26/ui/native-workspace.js','src/m26/ui/progress-continuity.js','src/m26/ui/session-readiness.js','src/m26/workflows/iri-report-document.js','src/m26/workflows/report-workflow.js','public/m26/app.js','public/m26/index.html'];
  for(const file of files){const s=await read(file);if(forbidden.some((r)=>r.test(s)))return false;}
  return existsSync('src/m26/design/runtime-static.css')&&existsSync('public/m26/preauth-critical.css');
}
if(await scanClean()){console.log('CSP staticization already applied');process.exit(0);}
const originals=new Map();
for(const p of ['src/m26/admin/route-render.js','src/m26/app/workflow-controller-base.js','src/m26/app/workflow-controller.js','src/m26/communication/view-model.js','src/m26/modules/route-render-base.js','src/m26/modules/route-render.js','src/m26/onboarding/client-contextual-guide.js','src/m26/onboarding/client-guided-welcome.js','src/m26/onboarding/guided-tour.js','src/m26/rc39/shell-enhancer.js','src/m26/shell/shell-render.js','src/m26/ui/client-360.js','src/m26/ui/exercise-history-window.js','src/m26/ui/native-workspace.js','src/m26/ui/progress-continuity.js','src/m26/ui/session-readiness.js','src/m26/workflows/iri-report-document.js','src/m26/workflows/report-workflow.js','public/m26/app.js','public/m26/index.html']) originals.set(p,await read(p));
const get=(p)=>originals.get(p);const sections=[];const add=(title,css)=>sections.push(`\n/* === ${title} === */\n${css.trim()}\n`);
add('Admin danger zone',extractBetween(get('src/m26/admin/route-render.js'),'const dangerStyle=`<style>','</style>`','admin danger'));
add('Commercial portfolio',extractBetween(get('src/m26/communication/view-model.js'),'style.textContent=`','`;','portfolio css'));
add('Guided tour',extractTemplate(get('src/m26/onboarding/guided-tour.js'),'STYLE_TEXT'));
add('Client contextual guide',extractTemplate(get('src/m26/onboarding/client-contextual-guide.js'),'STYLE'));
add('Client guided welcome',extractTemplate(get('src/m26/onboarding/client-guided-welcome.js'),'STYLE'));
add('Workspace shell v2',extractBetween(get('src/m26/shell/shell-render.js'),'return `<style data-m26-workspace-v2>','</style>`','shell css'));
add('Mobile shell polish',extractTemplate(get('src/m26/rc39/shell-enhancer.js'),'MOBILE_SHELL_POLISH'));
add('Client 360',extractTemplate(get('src/m26/ui/client-360.js'),'CLIENTE_360_CSS'));
add('Exercise history window',extractTemplate(get('src/m26/ui/exercise-history-window.js'),'STYLES'));
add('Native workspace',extractTemplate(get('src/m26/ui/native-workspace.js'),'NATIVE_WORKSPACE_CSS'));
add('Progress continuity',extractTemplate(get('src/m26/ui/progress-continuity.js'),'STYLES'));
add('Session readiness',extractTemplate(get('src/m26/ui/session-readiness.js'),'STYLES'));
add('Premium report editor',extractBetween(get('src/m26/workflows/report-workflow.js'),"style.textContent='","';document.head.append(style);",'premium report css'));
add('Session value loop',extractTemplate(get('public/m26/app.js'),'SESSION_VALUE_STYLES'));
add('IRI progress states',`.m26-progress-track>[data-iri-progress][data-progress-step="1"]{width:14.2857%}\n.m26-progress-track>[data-iri-progress][data-progress-step="2"]{width:28.5714%}\n.m26-progress-track>[data-iri-progress][data-progress-step="3"]{width:42.8571%}\n.m26-progress-track>[data-iri-progress][data-progress-step="4"]{width:57.1429%}\n.m26-progress-track>[data-iri-progress][data-progress-step="5"]{width:71.4286%}\n.m26-progress-track>[data-iri-progress][data-progress-step="6"]{width:85.7143%}\n.m26-progress-track>[data-iri-progress][data-progress-step="7"]{width:100%}`);
add('CSP-safe guide placement',`@media(min-width:691px){\n.m26-client-context-guide{left:auto;right:1rem;top:auto;bottom:1rem}\n.m26-client-context-guide[data-m26-guide-placement="top"]{top:1rem;bottom:auto}\n.m26-client-guide-presence{left:auto;right:1rem;top:1rem}\n.m26-client-guided-welcome{left:auto;right:1rem;top:auto;bottom:1rem}\n.m26-client-guided-welcome[data-m26-guide-placement="top"]{top:1rem;bottom:auto}\n.m26-client-guided-welcome-presence{left:auto;right:1.15rem;top:auto;bottom:17rem}\n.m26-client-guided-welcome-presence[data-m26-guide-placement="top"]{top:17rem;bottom:auto}\n}\n@media(max-width:690px){.m26-client-guide-presence,.m26-client-guided-welcome-presence{left:auto;right:.75rem;top:max(.75rem,env(safe-area-inset-top));bottom:auto}}\n.m26-client-guide-presence,.m26-client-guided-welcome-presence{transition:opacity 170ms ease,transform 230ms ease;will-change:opacity,transform}`);
await write('src/m26/design/runtime-static.css','/* IBERFIT M26 · CSP-safe first-party runtime styles. Static same-origin stylesheet; no inline/runtime CSS. */\n'+sections.join(''));
{
 let s=get('public/m26/index.html');const a=s.indexOf('  <style data-iberfit-preauth-critical>');const b=s.indexOf('</style>\n',a);if(a<0||b<0)throw new Error('preauth inline style not found');const css=s.slice(a+'  <style data-iberfit-preauth-critical>'.length,b);await write('public/m26/preauth-critical.css','/* IBERFIT M26 · critical pre-auth styles; externalized for strict CSP. */\n'+css.trim()+'\n');s=s.slice(0,a)+'  <link rel="stylesheet" href="/m26/preauth-critical.css" data-iberfit-preauth-critical>\n'+s.slice(b+'</style>\n'.length);const anchor='  <link rel="stylesheet" data-href="/src/m26/shell/shell.css" data-iberfit-full-style media="not all">\n';s=replaceOnce(s,anchor,anchor+'  <link rel="stylesheet" data-href="/src/m26/design/runtime-static.css" data-iberfit-full-style data-iberfit-runtime-static media="not all">\n','runtime css link');await write('public/m26/index.html',s);
}
{
 let s=get('src/m26/admin/route-render.js');const a=s.indexOf('\n  const dangerStyle=`<style>');const b=s.indexOf('</style>`;',a);if(a<0||b<0)throw new Error('admin danger style not found');s=s.slice(0,a)+s.slice(b+'</style>`;'.length);s=replaceOnce(s,'return `<div class="m26-admin-route">${dangerStyle}${intro(','return `<div class="m26-admin-route">${intro(','admin danger render');await write('src/m26/admin/route-render.js',s);
}
{
 let s=get('src/m26/communication/view-model.js');s=replaceFunction(s,'function ensurePortfolioStyles(documentLike)',"function ensurePortfolioStyles(documentLike){\n  return documentLike?.querySelector?.('[data-iberfit-runtime-static]')||null;\n}",'portfolio styles');await write('src/m26/communication/view-model.js',s);
}
{
 let s=get('src/m26/onboarding/guided-tour.js');s=replaceFunction(s,'function ensureStyle(documentLike)',"function ensureStyle(documentLike){\n  return documentLike?.querySelector?.('[data-iberfit-runtime-static]')||null;\n}",'tour styles');await write('src/m26/onboarding/guided-tour.js',s);
}
{
 let s=get('src/m26/onboarding/client-contextual-guide.js');s=replaceFunction(s,'function ensureStyle(doc)',"function ensureStyle(doc){\n  return doc?.querySelector?.('[data-iberfit-runtime-static]')||null;\n}",'context styles');const a=s.indexOf('function positionPresence('),b=s.indexOf('\nfunction dialogHtml',a);if(a<0||b<0)throw new Error('context positionPresence block');const pos=`function positionPresence(node,targetNode,scope,{arriving=false}={}){\n  if(!node||!targetNode)return false;\n  try{\n    const rect=targetNode.getBoundingClientRect?.();const width=Number(scope?.innerWidth||0);const height=Number(scope?.innerHeight||0);if(!rect||!width||!height)return false;\n    const mobile=width<=690;const margin=mobile?10:14;const bottomReserve=mobile?104:margin;const outside=Number(rect.bottom||0)<margin||Number(rect.top||0)>height-bottomReserve||Number(rect.right||0)<0||Number(rect.left||0)>width;\n    if(outside){hidePresence(node);return false;}\n    node.setAttribute?.('data-m26-guide-placement',Number(rect.top||0)>height/2?'top':'bottom');node.setAttribute?.('data-m26-client-guide-positioned','true');node.classList?.add?.('is-visible');\n    if(!arriving)node.classList?.remove?.('is-arriving');if(arriving&&!reduced(scope)){node.classList?.remove?.('is-arriving');void node.offsetWidth;node.classList?.add?.('is-arriving');}\n    return true;\n  }catch{return false;}\n}\n`;s=s.slice(0,a)+pos+s.slice(b);const c=s.indexOf('function positionDialog('),d=s.indexOf('\n\nexport function createClientContextualGuideController',c);if(c<0||d<0)throw new Error('context positionDialog block');const dlg=`function positionDialog(dialog,node,scope){\n  if(!dialog||!node)return;\n  try{const height=Number(scope?.innerHeight||0);const rect=node.getBoundingClientRect?.();dialog.setAttribute?.('data-m26-guide-placement',height&&Number(rect?.top||0)>height/2?'top':'bottom');}\n  catch{dialog.setAttribute?.('data-m26-guide-placement','bottom');}\n}\n`;s=s.slice(0,c)+dlg+s.slice(d);await write('src/m26/onboarding/client-contextual-guide.js',s);
}
{
 let s=get('src/m26/onboarding/client-guided-welcome.js');s=replaceFunction(s,'function ensureStyle(doc)',"function ensureStyle(doc){\n  return doc?.querySelector?.('[data-iberfit-runtime-static]')||null;\n}",'welcome styles');const a=s.indexOf('function position(node,target,scope'),b=s.indexOf('\n\nexport function createClientGuidedWelcomeController',a);if(a<0||b<0)throw new Error('welcome position block');const pos=`function position(node,target,scope,{arriving=false,dialog=null}={}){\n  if(!node||!target)return false;\n  try{const rect=target.getBoundingClientRect?.();const width=Number(scope?.innerWidth||0);const height=Number(scope?.innerHeight||0);if(!rect||!width||!height)return false;const mobile=width<=690;const margin=mobile?10:14;const bottomReserve=mobile?96:margin;const outside=Number(rect.bottom||0)<margin||Number(rect.top||0)>height-bottomReserve||Number(rect.right||0)<0||Number(rect.left||0)>width;if(outside){node.classList?.remove?.('is-visible','is-arriving');return false;}\n    const side=Number(rect.left||0)<width/2?'right':'left';const placement=Number(rect.top||0)>height/2?'top':'bottom';node.setAttribute?.('data-m26-client-guide-side',side);node.setAttribute?.('data-m26-guide-placement',placement);dialog?.setAttribute?.('data-m26-client-guide-side',side);dialog?.setAttribute?.('data-m26-guide-placement',placement);node.classList?.add?.('is-visible');if(arriving&&!reduced(scope)){node.classList?.remove?.('is-arriving');void node.offsetWidth;node.classList?.add?.('is-arriving');}else node.classList?.remove?.('is-arriving');return true;\n  }catch{return false;}\n}\n`;s=s.slice(0,a)+pos+s.slice(b);const c=s.indexOf('  function schedulePosition(){'),d=s.indexOf('\n  function show(',c);if(c<0||d<0)throw new Error('welcome schedulePosition block');const schedule=`  function schedulePosition(){\n    if(positionFrame!==null||!activeTarget)return;\n    const run=()=>{positionFrame=null;if(dialog&&activeTarget){try{const rect=activeTarget.getBoundingClientRect?.();const height=Number(scope?.innerHeight||0);dialog.setAttribute?.('data-m26-guide-placement',height&&Number(rect?.top||0)>height/2?'top':'bottom');}catch{}}if(presence&&activeTarget)position(presence,activeTarget,scope,{dialog});};\n    if(typeof scope?.requestAnimationFrame==='function')positionFrame=scope.requestAnimationFrame(run);else queueMicrotask(run);\n  }\n`;s=s.slice(0,c)+schedule+s.slice(d);await write('src/m26/onboarding/client-guided-welcome.js',s);
}
{
 let s=get('src/m26/shell/shell-render.js');const a=s.indexOf('function shellStyles(){'),b=s.indexOf('\n\nexport function',a);if(a<0||b<0)throw new Error('shellStyles block');s=s.slice(0,a)+"function shellStyles(){return '';}"+s.slice(b);await write('src/m26/shell/shell-render.js',s);let r=get('src/m26/rc39/shell-enhancer.js');r=replaceOnce(r,"  if(out.includes('<style data-m26-workspace-v2>')){\n    out=out.replace('</style>',`${MOBILE_SHELL_POLISH}</style>`);\n  }\n",'','rc39 inline shell polish');await write('src/m26/rc39/shell-enhancer.js',r);
}
for(const [p,sig] of [['src/m26/ui/client-360.js','function installStyles(document)'],['src/m26/ui/exercise-history-window.js','function installStyles(documentLike)'],['src/m26/ui/progress-continuity.js','function installStyles(document)'],['src/m26/ui/session-readiness.js','function installStyles(document)']]){let s=get(p);s=replaceFunction(s,sig,`${sig}{\n  return true;\n}`,p);await write(p,s);}
{
 let s=get('src/m26/ui/native-workspace.js');s=replaceFunction(s,'export function ensureNativeWorkspaceStyles(doc=globalThis.document)',"export function ensureNativeWorkspaceStyles(doc=globalThis.document){\n  return Boolean(doc?.head);\n}",'native styles');await write('src/m26/ui/native-workspace.js',s);
}
{
 let s=get('src/m26/workflows/report-workflow.js');s=replaceFunction(s,'function ensurePremiumReportStyles(document)',"function ensurePremiumReportStyles(document){\n  return Boolean(document?.head);\n}",'premium report styles');await write('src/m26/workflows/report-workflow.js',s);
}
{
 let s=get('public/m26/app.js');s=replaceFunction(s,'function installSessionValueStyles(document)',"function installSessionValueStyles(document){\n  return Boolean(document?.head);\n}",'session value styles');await write('public/m26/app.js',s);
}
{
 let s=get('src/m26/workflows/iri-report-document.js');const old=`  const stylesheet=externalStylesheet\n    ?\`<link rel="stylesheet" href="\${escapeHtml(externalStylesheet)}" data-iri-report-stylesheet>\`\n    :\`<style>\${REPORT_STYLESHEET}</style>\`;`;const next=`  const stylesheetHrefSafe=externalStylesheet||'/m26/iri-report.css?v=m26-rc45-6-launch-hardening-v1';\n  const stylesheet=\`<link rel="stylesheet" href="\${escapeHtml(stylesheetHrefSafe)}" data-iri-report-stylesheet>\`;`;s=replaceOnce(s,old,next,'iri report external stylesheet');await write('src/m26/workflows/iri-report-document.js',s);
}
for(const p of ['src/m26/modules/route-render.js','src/m26/modules/route-render-base.js']){let s=get(p);s=replaceOnce(s,'data-iri-progress style="width:14.3%"','data-iri-progress data-progress-step="1"',`${p} iri progress`);await write(p,s);}
for(const p of ['src/m26/app/workflow-controller.js','src/m26/app/workflow-controller-base.js']){let s=get(p);const old="const progress=form.querySelector?.('[data-iri-progress]');if(progress)progress.style.width=`${Math.round(((bounded+1)/IRI_FIRST_SESSION_STEPS.length)*1000)/10}%`;";const next="const progress=form.querySelector?.('[data-iri-progress]');if(progress)progress.setAttribute?.('data-progress-step',String(bounded+1));";s=replaceOnce(s,old,next,`${p} iri progress update`);await write(p,s);}
if(!(await scanClean()))throw new Error('CSP staticization finished but scanner is not clean');
console.log('CSP staticization applied successfully');
