import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd();
const buildRoot=path.join(root,process.env.M26_BUILD_DIR||'dist/m26-prepublicacion-infraestructura-candidate');
const reportPath=path.join(root,'recovery','RC442_BUILD_VERIFICATION.json');
const BRANCH='canary/rc44-zero-cost-wearables';
const PROJECT_REF='tvqnvvwaddcuehqmzvty';
const PRODUCTION_REF='pjhmrhejsoofmouedavw';
const VERSION='26.0.0-canary.44.2-stable-wearables';
const RELEASE='IBERFIT_M26_CANARY_RC44_2_STABLE_WEARABLES';
const SW_VERSION='m26-rc44-2-stable-wearables-canary-v1';
const RC44_SW_VERSION='m26-rc44-zero-cost-wearables-canary-v1';
const RC431_SW_VERSION='m26-rc43-1-draft-persistence-canary-v1';
const commit=String(process.env.CF_PAGES_COMMIT_SHA||'').trim();
const branch=String(process.env.CF_PAGES_BRANCH||'').trim();
if(!/^[0-9a-f]{40}$/u.test(commit))throw new Error('RC442_COMMIT_REQUIRED');
if(branch!==BRANCH)throw new Error(`RC442_BRANCH_REQUIRED:${BRANCH}`);
const file=(...parts)=>path.join(buildRoot,...parts);
const required={version:file('version.json'),runtime:file('m26','runtime-config.js'),worker:file('m26','sw.js'),route:file('src','m26','modules','route-render.js'),viewModel:file('src','m26','wearables','view-model.js'),normalization:file('src','m26','wearables','normalization.js'),css:file('src','m26','rc44','rc44.css')};
for(const [name,target] of Object.entries(required))if(!fs.existsSync(target))throw new Error(`RC442_ARTIFACT_MISSING:${name}`);
const read=(target)=>fs.readFileSync(target,'utf8');
const write=(target,value)=>fs.writeFileSync(target,value,'utf8');
let version=JSON.parse(read(required.version));
if(version.backendContract!=='RC44'||version.productionModified!==false||version.productionDeployed!==false||version.qaOnly!==true)throw new Error('RC442_VERSION_SAFETY_INVALID');
version={...version,version:VERSION,release:RELEASE,sourceRelease:'RC44.2',commit,branch,builtAt:new Date().toISOString(),productionModified:false,productionDeployed:false};
write(required.version,`${JSON.stringify(version,null,2)}\n`);
let runtimeSource=read(required.runtime);
const runtimeMatch=runtimeSource.match(/Object\.freeze\((\{[\s\S]*\})\);\s*$/u);
if(!runtimeMatch)throw new Error('RC442_RUNTIME_FORMAT_INVALID');
const runtime=JSON.parse(runtimeMatch[1]);
if(runtime.projectRef!==PROJECT_REF||runtime.url!==`https://${PROJECT_REF}.supabase.co`||runtime.enabled!==true||runtime.qaOnly!==true||!Array.isArray(runtime.allowedHosts)||runtimeSource.includes(PRODUCTION_REF))throw new Error('RC442_RUNTIME_SAFETY_INVALID');
const nextRuntime={...runtime,version:VERSION};
runtimeSource=runtimeSource.replace(runtimeMatch[1],JSON.stringify(nextRuntime,null,2));
write(required.runtime,runtimeSource);
let worker=read(required.worker);
if(!worker.includes(RC44_SW_VERSION))throw new Error('RC442_SW_BASE_VERSION_MISSING');
worker=worker.replaceAll(RC44_SW_VERSION,SW_VERSION).replaceAll(RC431_SW_VERSION,RC44_SW_VERSION);
worker=worker.replace("self.addEventListener('install',(event)=>event.waitUntil(installShell()));","self.addEventListener('install',(event)=>event.waitUntil(installShell().then(()=>self.skipWaiting())));");
write(required.worker,worker);
const route=read(required.route),viewModel=read(required.viewModel),normalization=read(required.normalization),css=read(required.css);
const failures=[];
if(!route.includes('Últimos registros diarios')||!route.includes('Todo lo gratuito que puede usarse ahora')||route.includes('renderClientBottomNav(vm)}</div>')||!route.includes('.tsv,application/json'))failures.push('route');
if(!viewModel.includes('dailyRecords:summary.records'))failures.push('view-model');
if(!normalization.includes('ASYNC_BATCH_SIZE=250')||!normalization.includes("['records','days','activities','summaries','daily','data']"))failures.push('normalization');
if(!css.includes('.m26-client-bottom-nav-layer{display:none!important}')||!css.includes('RC44.2 · estabilidad de shell'))failures.push('css');
if(!worker.includes(SW_VERSION)||worker.includes(RC431_SW_VERSION)||!worker.includes('installShell().then(()=>self.skipWaiting())'))failures.push('service-worker');
const finalRuntime=read(required.runtime),finalVersion=read(required.version);
if(finalRuntime.includes(PRODUCTION_REF)||finalVersion.includes(PRODUCTION_REF))failures.push('production-ref');
if(failures.length)throw new Error(`RC442_FINALIZE_INVALID:${failures.join(',')}`);
const hashes=Object.fromEntries(Object.entries(required).map(([name,target])=>[name,crypto.createHash('sha256').update(fs.readFileSync(target)).digest('hex')]));
fs.mkdirSync(path.dirname(reportPath),{recursive:true});
fs.writeFileSync(reportPath,`${JSON.stringify({ok:true,release:RELEASE,version:VERSION,branch,commit,projectRef:PROJECT_REF,backendContract:'RC44',productionModified:false,productionDeployed:false,hashes},null,2)}\n`,'utf8');
console.log(JSON.stringify({ok:true,release:RELEASE,version:VERSION,branch,commit,projectRef:PROJECT_REF,serviceWorker:SW_VERSION,reportPath,productionModified:false,productionDeployed:false},null,2));
