import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const ROOT=process.cwd();
const SOURCE=path.join(ROOT,'src/m26/design/tokens.json');
const OUTPUTS=Object.freeze({
  js:path.join(ROOT,'src/m26/design/tokens.generated.js'),
  css:path.join(ROOT,'src/m26/design/tokens.css'),
  phone:path.join(ROOT,'native/android-host/phone-app/src/main/res/values/iberfit_design_tokens.xml'),
  wear:path.join(ROOT,'native/android-host/wear-app/src/main/res/values/iberfit_design_tokens.xml'),
});

function fail(code){throw new Error(code);}
function getPath(root,key){
  let current=root;
  for(const part of String(key).split('.')){
    if(!current||!Object.prototype.hasOwnProperty.call(current,part))fail(`RC58_TOKEN_REFERENCE_MISSING:${key}`);
    current=current[part];
  }
  return current;
}
function resolveValue(root,value,stack=[]){
  if(typeof value==='string'){
    const match=value.match(/^\{([^}]+)\}$/);
    if(!match)return value;
    if(stack.includes(match[1]))fail(`RC58_TOKEN_REFERENCE_CYCLE:${[...stack,match[1]].join('>')}`);
    return resolveValue(root,getPath(root,match[1]),[...stack,match[1]]);
  }
  if(Array.isArray(value))return value.map((item)=>resolveValue(root,item,stack));
  if(value&&typeof value==='object'){
    return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,resolveValue(root,item,stack)]));
  }
  return value;
}
function resolveTokens(raw){return resolveValue(raw,raw);}
function numberText(value){
  const numeric=Number(value);
  if(!Number.isFinite(numeric))fail(`RC58_TOKEN_NUMBER_REQUIRED:${value}`);
  return Number.isInteger(numeric)?String(numeric):String(Number(numeric.toFixed(4)));
}
function rem(px){return `${numberText(Number(px)/16)}rem`;}
function px(value){return `${numberText(value)}px`;}
function ms(value){return `${numberText(value)}ms`;}
function cssVar(name,value){return `  --iberfit-${name}: ${value};`;}
function rgbaToAndroid(value){
  const hex=String(value).match(/^#([0-9a-f]{6})$/i);
  if(hex)return `#FF${hex[1].toUpperCase()}`;
  const rgba=String(value).match(/^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(0(?:\.\d+)?|1(?:\.0+)?)\s*\)$/i);
  if(!rgba)fail(`RC58_ANDROID_COLOR_UNSUPPORTED:${value}`);
  const channels=rgba.slice(1,4).map((item)=>Number(item));
  if(channels.some((item)=>item<0||item>255))fail(`RC58_ANDROID_COLOR_RANGE:${value}`);
  const alpha=Math.round(Number(rgba[4])*255);
  const h=(number)=>number.toString(16).padStart(2,'0').toUpperCase();
  return `#${h(alpha)}${channels.map(h).join('')}`;
}
function xmlEscape(value){
  return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
}
function ensureRequired(t){
  const required=[
    'version','color.primitive.forest950','color.primitive.forest900','color.primitive.gold500',
    'color.primitive.gold300','color.primitive.cream100','color.primitive.cream300',
    'color.semantic.canvas','color.semantic.textPrimary','color.semantic.textSecondary',
    'color.semantic.border','color.semantic.focus','space.4','radius.sm',
    'size.touchTargetPx','motion.duration.standardMs','breakpoint.mobilePx','breakpoint.tabletPx'
  ];
  for(const key of required)getPath(t,key);
  if(Number(t.size.touchTargetPx)<44)fail('RC58_TOUCH_TARGET_BELOW_44');
  const series=Object.entries(t.color.dataViz).filter(([key])=>key.startsWith('series')).map(([,value])=>value);
  if(series.length<6||new Set(series).size!==series.length)fail('RC58_DATA_VIZ_SERIES_REQUIRED');
}
function buildJs(t){
  return `/* AUTO-GENERATED by scripts/generate_rc58_design_tokens.mjs. Do not edit. */\n`+
`function deepFreeze(value){\n`+
`  if(value&&typeof value==='object'&&!Object.isFrozen(value)){\n`+
`    Object.freeze(value);\n`+
`    for(const item of Object.values(value))deepFreeze(item);\n`+
`  }\n`+
`  return value;\n`+
`}\n\n`+
`export const IBERFIT_DESIGN_TOKENS=deepFreeze(${JSON.stringify(t,null,2)});\n`;
}
function buildCss(t){
  const p=t.color.primitive,s=t.color.semantic,r=t.color.role,d=t.color.dataViz;
  const lines=[
    '/* AUTO-GENERATED by scripts/generate_rc58_design_tokens.mjs. Do not edit. */',
    ':root {',
    '  color-scheme: dark;',
    cssVar('color-forest-950',p.forest950),
    cssVar('color-forest-900',p.forest900),
    cssVar('color-forest-800',p.forest800),
    cssVar('color-forest-700',p.forest700),
    cssVar('color-gold-500',p.gold500),
    cssVar('color-gold-300',p.gold300),
    cssVar('color-cream-100',p.cream100),
    cssVar('color-cream-300',p.cream300),
    cssVar('color-muted',p.muted),
    cssVar('color-canvas',s.canvas),
    cssVar('color-surface-base',s.surfaceBase),
    cssVar('color-surface-raised',s.surfaceRaised),
    cssVar('color-surface-overlay',s.surfaceOverlay),
    cssVar('color-text-primary',s.textPrimary),
    cssVar('color-text-secondary',s.textSecondary),
    cssVar('color-text-subtle',s.textSubtle),
    cssVar('color-accent',s.accent),
    cssVar('color-accent-strong',s.accentStrong),
    cssVar('color-border',s.border),
    cssVar('color-border-strong',s.borderStrong),
    cssVar('color-focus',s.focus),
    cssVar('color-success',s.success),
    cssVar('color-warning',s.warning),
    cssVar('color-danger',s.danger),
    cssVar('color-info',s.info),
    cssVar('color-role-admin-accent',r.adminAccent),
    cssVar('color-role-admin-accent-soft',r.adminAccentSoft),
    cssVar('data-series-1',d.series1),
    cssVar('data-series-2',d.series2),
    cssVar('data-series-3',d.series3),
    cssVar('data-series-4',d.series4),
    cssVar('data-series-5',d.series5),
    cssVar('data-series-6',d.series6),
    cssVar('data-grid',d.grid),
    cssVar('data-missing',d.missing),
  ];
  for(const [key,value] of Object.entries(t.space))lines.push(cssVar(`space-${key}`,rem(value)));
  for(const [key,value] of Object.entries(t.radius))lines.push(cssVar(`radius-${key}`,key==='pill'?px(value):rem(value)));
  for(const [key,value] of Object.entries(t.shadow))lines.push(cssVar(`shadow-${key}`,value));
  lines.push(cssVar('font-family-ui',t.typography.family.ui));
  lines.push(cssVar('font-family-editorial',t.typography.family.editorial));
  for(const [key,value] of Object.entries(t.typography.sizePx))lines.push(cssVar(`font-size-${key}`,rem(value)));
  for(const [key,value] of Object.entries(t.typography.weight))lines.push(cssVar(`font-weight-${key}`,numberText(value)));
  for(const [key,value] of Object.entries(t.typography.lineHeight))lines.push(cssVar(`line-height-${key}`,numberText(value)));
  for(const [key,value] of Object.entries(t.motion.duration))lines.push(cssVar(`motion-${key.replace(/Ms$/,'').replace(/[A-Z]/g,(m)=>`-${m.toLowerCase()}`)}`,ms(value)));
  for(const [key,value] of Object.entries(t.motion.easing))lines.push(cssVar(`motion-easing-${key}`,value));
  lines.push(cssVar('size-touch-target',px(t.size.touchTargetPx)));
  lines.push(cssVar('size-touch-target-comfortable',px(t.size.touchTargetComfortablePx)));
  lines.push(cssVar('layout-content-max',px(t.layout.contentMaxPx)));
  lines.push(cssVar('layout-mobile-nav-height',px(t.layout.mobileNavHeightPx)));
  for(const [key,value] of Object.entries(t.zIndex))lines.push(cssVar(`z-${key.replace(/[A-Z]/g,(m)=>`-${m.toLowerCase()}`)}`,numberText(value)));
  for(const [role,values] of Object.entries(t.density)){
    lines.push(cssVar(`density-${role}-control-min`,px(values.controlMinPx)));
    lines.push(cssVar(`density-${role}-gap`,px(values.gapPx)));
  }
  lines.push('');
  lines.push('  /* Compatibility aliases. Legacy components migrate incrementally in RC58. */');
  lines.push('  --m26-forest-950: var(--iberfit-color-forest-950);');
  lines.push('  --m26-forest-900: var(--iberfit-color-forest-900);');
  lines.push('  --m26-forest-800: var(--iberfit-color-forest-800);');
  lines.push('  --m26-forest-700: var(--iberfit-color-forest-700);');
  lines.push('  --m26-gold-500: var(--iberfit-color-gold-500);');
  lines.push('  --m26-gold-300: var(--iberfit-color-gold-300);');
  lines.push('  --m26-cream-100: var(--iberfit-color-cream-100);');
  lines.push('  --m26-cream-300: var(--iberfit-color-cream-300);');
  lines.push('  --m26-muted: var(--iberfit-color-text-secondary);');
  lines.push('  --m26-line: var(--iberfit-color-border);');
  lines.push('  --m26-danger: var(--iberfit-color-danger);');
  lines.push('  --m26-success: var(--iberfit-color-success);');
  lines.push('  --m26-focus: var(--iberfit-color-focus);');
  lines.push('  --m26-shadow: var(--iberfit-shadow-elevated);');
  lines.push('  --m26-sans: var(--iberfit-font-family-ui);');
  lines.push('  --m26-serif: var(--iberfit-font-family-editorial);');
  lines.push('  --m26-radius-sm: var(--iberfit-radius-sm);');
  lines.push('  --m26-radius-md: var(--iberfit-radius-md);');
  lines.push('  --m26-radius-lg: var(--iberfit-radius-lg);');
  lines.push('  --m26-touch-target: var(--iberfit-size-touch-target);');
  lines.push('  --m26-content-max: var(--iberfit-layout-content-max);');
  lines.push('  --m26-mobile-nav-height: var(--iberfit-layout-mobile-nav-height);');
  lines.push('  --m26-transition: var(--iberfit-motion-standard) var(--iberfit-motion-easing-standard);');
  lines.push('  --m26-accent: var(--iberfit-color-success);');
  lines.push('  --m26-text-muted: var(--iberfit-color-text-secondary);');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
function buildAndroidXml(t){
  const colors={
    iberfit_color_canvas:t.color.semantic.canvas,
    iberfit_color_surface_base:t.color.semantic.surfaceBase,
    iberfit_color_surface_raised:t.color.semantic.surfaceRaised,
    iberfit_color_text_primary:t.color.semantic.textPrimary,
    iberfit_color_text_secondary:t.color.semantic.textSecondary,
    iberfit_color_accent:t.color.semantic.accent,
    iberfit_color_accent_strong:t.color.semantic.accentStrong,
    iberfit_color_border:t.color.semantic.border,
    iberfit_color_focus:t.color.semantic.focus,
    iberfit_color_success:t.color.semantic.success,
    iberfit_color_warning:t.color.semantic.warning,
    iberfit_color_danger:t.color.semantic.danger,
    iberfit_color_info:t.color.semantic.info,
    iberfit_color_admin_accent:t.color.role.adminAccent,
  };
  const lines=[
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- AUTO-GENERATED by scripts/generate_rc58_design_tokens.mjs. Do not edit. -->',
    '<resources>'
  ];
  for(const [name,value] of Object.entries(colors))lines.push(`    <color name="${name}">${xmlEscape(rgbaToAndroid(value))}</color>`);
  for(const [key,value] of Object.entries(t.space))lines.push(`    <dimen name="iberfit_space_${key}">${numberText(value)}dp</dimen>`);
  for(const [key,value] of Object.entries(t.radius))if(key!=='pill')lines.push(`    <dimen name="iberfit_radius_${key}">${numberText(value)}dp</dimen>`);
  lines.push(`    <dimen name="iberfit_touch_target">${numberText(t.size.touchTargetPx)}dp</dimen>`);
  lines.push(`    <dimen name="iberfit_touch_target_comfortable">${numberText(t.size.touchTargetComfortablePx)}dp</dimen>`);
  lines.push('</resources>');
  lines.push('');
  return lines.join('\n');
}
function normalizeEol(value){return String(value).replace(/\r\n/g,'\n');}
function writeOrCheck(file,content,check){
  const normalized=normalizeEol(content);
  if(check){
    if(!fs.existsSync(file))fail(`RC58_GENERATED_FILE_MISSING:${path.relative(ROOT,file)}`);
    if(normalizeEol(fs.readFileSync(file,'utf8'))!==normalized)fail(`RC58_GENERATED_FILE_STALE:${path.relative(ROOT,file)}`);
    return;
  }
  fs.mkdirSync(path.dirname(file),{recursive:true});
  fs.writeFileSync(file,normalized,'utf8');
}
const raw=JSON.parse(fs.readFileSync(SOURCE,'utf8'));
ensureRequired(raw);
const resolved=resolveTokens(raw);
ensureRequired(resolved);
const check=process.argv.includes('--check');
writeOrCheck(OUTPUTS.js,buildJs(resolved),check);
writeOrCheck(OUTPUTS.css,buildCss(resolved),check);
const android=buildAndroidXml(resolved);
writeOrCheck(OUTPUTS.phone,android,check);
writeOrCheck(OUTPUTS.wear,android,check);
console.log(`RC58_DESIGN_TOKEN_GENERATION=${check?'CHECK_PASS':'PASS'}`);
console.log(`RC58_DESIGN_TOKEN_VERSION=${resolved.version}`);
console.log('RC58_TOKEN_SINGLE_SOURCE=src/m26/design/tokens.json');