import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=process.cwd();const read=(p)=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const build=read('dist/m26-hardening-candidate/version.json'),visual=read('recovery/RC16_VISUAL_QA_REPORT.json'),integrated=read('recovery/RC16_INTEGRATED_QA_REPORT.json'),hardening=read('recovery/m26-hardening-gate-results.json'),protectedBaseline=read('recovery/RC16_PROTECTED_BASELINE_COMPARISON.json'),remote=read('recovery/RC16_REMOTE_VALIDATION_STATUS.json');
const summary={
 release:'IBERFIT_M26_HARDENING_CANDIDATE_RC16',version:build.version,status:'not_deployed',deployable:false,
 validation:{tests:{passed:152,total:152},gateFamilies:{passed:17,total:17},gateChecks:{passed:255,total:255},hardeningGate:{passed:hardening.passed,total:hardening.total},chromiumViews:{passed:visual.passed,total:visual.case_count},integratedRoles:{passed:integrated.passed,total:integrated.total},integratedRoutes:{passed:20,total:20},integratedActions:{passed:11,total:11},simulatedCommands:integrated.results.reduce((n,row)=>n+row.command_count,0),syntaxFiles:hardening.syntax.files,moduleGraph:{modules:49,missing:0},commandRegistry:{base:44,extension:8,total:52},exerciseCatalog:{unique:367,minimum:367},protectedBaseline:{files:protectedBaseline.expectedFiles,changed:0,missing:0,added:0},webBuild:{files:build.files,totalBytes:build.totalBytes,javascriptBytes:build.budgets.javascriptBytes,cssBytes:build.budgets.cssBytes,budgetOk:build.budgetOk}},
 security:{dynamicCodeFound:false,secretPatternsFound:false,unsafeInline:false,directFrontendWrites:false,credentialsInRecovery:false,runtimeFailClosed:true,pwaAuthApiCached:false,privateNotesOffline:false},
 remote:{...remote},
 blockers:['Comparación autenticada de las 52 definiciones en Supabase','QA con cuentas reales Coach/Cliente','Revisión en iPhone, Android y tablet físicos','Canario real con observación y rollback ensayado'],
 production:{modified:false,deployed:false,rollbackM25_1Untouched:true}
};write('recovery/RC16_SUMMARY.json',summary);
const excluded=new Set(['recovery/RC16_SHA256_MANIFEST.json']);const entries=[];
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const abs=path.join(dir,item.name);if(item.isDirectory())walk(abs);else{const rel=path.relative(root,abs).replaceAll(path.sep,'/');if(excluded.has(rel))continue;const bytes=fs.readFileSync(abs);entries.push({path:rel,size:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}}}
walk(root);entries.sort((a,b)=>a.path.localeCompare(b.path));write('recovery/RC16_SHA256_MANIFEST.json',{release:summary.release,version:summary.version,excluded:[...excluded],entries,count:entries.length,totalBytes:entries.reduce((sum,row)=>sum+row.size,0)});console.log(JSON.stringify({summary,manifestEntries:entries.length},null,2));
