alter table public.operational_events drop constraint if exists operational_events_environment_check;
alter table public.backup_manifests drop constraint if exists backup_manifests_environment_check;
alter table public.preview_access drop constraint if exists preview_access_environment_check;
alter table public.beta_runs drop constraint if exists beta_runs_environment_check;
alter table public.release_candidates drop constraint if exists release_candidates_environment_check;
alter table public.beta_participants_v16 drop constraint if exists beta_participants_v16_environment_check;
alter table public.rollout_plans_v18 drop constraint if exists rollout_plans_v18_environment_check;
alter table public.operational_events alter column environment set default 'PRODUCTION';
alter table public.backup_manifests alter column environment set default 'PRODUCTION';
alter table public.preview_access alter column environment set default 'PRODUCTION';
alter table public.beta_runs alter column environment set default 'PRODUCTION';
alter table public.release_candidates alter column environment set default 'PRODUCTION';
alter table public.beta_participants_v16 alter column environment set default 'PRODUCTION';
alter table public.rollout_plans_v18 alter column environment set default 'PRODUCTION';
alter table public.feature_flags_v18 alter column environment set default 'PRODUCTION';
alter table public.operational_events add constraint operational_events_environment_check check (environment = 'PRODUCTION');
alter table public.backup_manifests add constraint backup_manifests_environment_check check (environment = 'PRODUCTION');
alter table public.preview_access add constraint preview_access_environment_check check (environment = 'PRODUCTION');
alter table public.beta_runs add constraint beta_runs_environment_check check (environment = 'PRODUCTION');
alter table public.release_candidates add constraint release_candidates_environment_check check (environment = 'PRODUCTION');
alter table public.beta_participants_v16 add constraint beta_participants_v16_environment_check check (environment = 'PRODUCTION');
alter table public.rollout_plans_v18 add constraint rollout_plans_v18_environment_check check (environment = 'PRODUCTION');;
