drop policy if exists operational_events_select on public.operational_events;
create policy operational_events_select on public.operational_events for select to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or actor_user_id = (select auth.uid()) or (client_id is not null and public.is_assigned_coach(client_id)));
drop policy if exists operational_events_insert on public.operational_events;
create policy operational_events_insert on public.operational_events for insert to authenticated with check (actor_user_id = (select auth.uid()) and environment = 'SYNTHETIC_ONLY' and ((select public.iberfit_role()) = 'admin'::public.iberfit_role or ((select public.iberfit_role()) = 'coach'::public.iberfit_role and client_id is not null and public.is_assigned_coach(client_id)) or ((select public.iberfit_role()) = 'client'::public.iberfit_role and client_id = (select public.iberfit_client_id()))));
drop policy if exists backup_manifests_select on public.backup_manifests;
create policy backup_manifests_select on public.backup_manifests for select to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or ((select public.iberfit_role()) = 'coach'::public.iberfit_role and client_id is not null and public.is_assigned_coach(client_id)) or created_by = (select auth.uid()));
drop policy if exists backup_manifests_insert on public.backup_manifests;
create policy backup_manifests_insert on public.backup_manifests for insert to authenticated with check (created_by = (select auth.uid()) and environment = 'SYNTHETIC_ONLY' and (select public.iberfit_role()) in ('coach'::public.iberfit_role, 'admin'::public.iberfit_role) and (client_id is null or public.is_assigned_coach(client_id)));
drop policy if exists preview_access_self_read on public.preview_access;
create policy preview_access_self_read on public.preview_access for select to authenticated using (user_id = (select auth.uid()) or (select public.iberfit_role()) = 'admin'::public.iberfit_role);
drop policy if exists preview_access_admin_all on public.preview_access;
create policy preview_access_admin_all on public.preview_access for all to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role) with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role);
drop policy if exists beta_runs_admin_all on public.beta_runs;
create policy beta_runs_admin_all on public.beta_runs for all to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role) with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role);;
