-- IBERFIT IRI v4 · physical-consent enforcement checkpoint
-- No-op by design.
--
-- The canonical trigger is created additively in:
--   20261002031500_iri_initial_photogrammetry_v1.sql
--
-- This later checkpoint intentionally performs no DDL. It exists only to preserve
-- release sequencing after an intermediate QA-only cutover experiment was retired.
-- Production must never need DROP/DO/recreate logic to enforce the physical-consent
-- guard: a clean application of the canonical migration already installs it.
