drop policy if exists session_events_client_insert on public.session_events;
drop policy if exists session_events_coach_insert on public.session_events;
drop policy if exists session_events_read on public.session_events;
create policy session_events_read on public.session_events for select to authenticated using (client_id = (select public.iberfit_client_id()) or public.is_assigned_coach(client_id));
create policy session_events_insert on public.session_events for insert to authenticated with check (actor_user_id = (select auth.uid()) and (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and event_type = any(array['SESION_INICIADA','SERIE_COMPLETADA','INCIDENCIA_REGISTRADA','CHECKIN_REGISTRADO','FEEDBACK_REGISTRADO','SESION_CERRADA','EJERCICIO_OMITIDO','EJERCICIO_REEMPLAZADO','EJERCICIO_AÑADIDO','DESCANSO_EDITADO']::text[]))));
drop policy if exists session_executions_client_insert on public.session_executions;
drop policy if exists session_executions_coach_write on public.session_executions;
drop policy if exists session_executions_read on public.session_executions;
create policy session_executions_read on public.session_executions for select to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id) or client_id = (select public.iberfit_client_id()));
create policy session_executions_insert on public.session_executions for insert to authenticated with check (((select public.iberfit_role()) in ('coach'::public.iberfit_role,'admin'::public.iberfit_role) and public.is_assigned_coach(client_id)) or (client_id = (select public.iberfit_client_id()) and started_by = (select auth.uid())));
create policy session_executions_update_coach on public.session_executions for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy session_executions_delete_coach on public.session_executions for delete to authenticated using (public.is_assigned_coach(client_id));
drop policy if exists iri_read on public.iri_assessments;
drop policy if exists iri_write on public.iri_assessments;
create policy iri_read on public.iri_assessments for select to authenticated using (public.is_assigned_coach(client_id));
create policy iri_insert_coach on public.iri_assessments for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy iri_update_coach on public.iri_assessments for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy iri_delete_coach on public.iri_assessments for delete to authenticated using (public.is_assigned_coach(client_id));
drop policy if exists reports_read on public.reports;
drop policy if exists reports_write on public.reports;
create policy reports_read on public.reports for select to authenticated using (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and status = 'publicado'::public.publication_status and audience = 'cliente'));
create policy reports_insert_coach on public.reports for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy reports_update_coach on public.reports for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy reports_delete_coach on public.reports for delete to authenticated using (public.is_assigned_coach(client_id));
drop policy if exists documents_read on public.documents;
drop policy if exists documents_write on public.documents;
create policy documents_read on public.documents for select to authenticated using (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and status = 'publicado'::public.publication_status and audience = 'cliente'));
create policy documents_insert_coach on public.documents for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy documents_update_coach on public.documents for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy documents_delete_coach on public.documents for delete to authenticated using (public.is_assigned_coach(client_id));;
