drop policy if exists intelligence_runs_coach_read on public.intelligence_runs;
drop policy if exists intelligence_runs_coach_write on public.intelligence_runs;
create policy intelligence_runs_coach_read on public.intelligence_runs for select to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy intelligence_runs_coach_insert on public.intelligence_runs for insert to authenticated with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy intelligence_runs_coach_update on public.intelligence_runs for update to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id)) with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy intelligence_runs_coach_delete on public.intelligence_runs for delete to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
drop policy if exists plan_change_proposals_coach_read on public.plan_change_proposals;
drop policy if exists plan_change_proposals_coach_write on public.plan_change_proposals;
create policy plan_change_proposals_coach_read on public.plan_change_proposals for select to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy plan_change_proposals_coach_insert on public.plan_change_proposals for insert to authenticated with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy plan_change_proposals_coach_update on public.plan_change_proposals for update to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id)) with check ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
create policy plan_change_proposals_coach_delete on public.plan_change_proposals for delete to authenticated using ((select public.iberfit_role()) = 'admin'::public.iberfit_role or public.is_assigned_coach(client_id));
drop policy if exists client_timeline_admin_all on public.client_timeline_events;
drop policy if exists client_timeline_client_published on public.client_timeline_events;
drop policy if exists client_timeline_coach_assigned on public.client_timeline_events;
create policy client_timeline_read on public.client_timeline_events for select to authenticated using ((select public.iberfit_current_role()) = 'admin'::public.iberfit_role or ((select public.iberfit_current_role()) = 'coach'::public.iberfit_role and public.iberfit_is_assigned_coach(client_id)) or ((select public.iberfit_current_role()) = 'client'::public.iberfit_role and (select public.iberfit_current_client_id()) = client_id and visibility = 'cliente'));
create policy client_timeline_admin_insert on public.client_timeline_events for insert to authenticated with check ((select public.iberfit_current_role()) = 'admin'::public.iberfit_role);
create policy client_timeline_admin_update on public.client_timeline_events for update to authenticated using ((select public.iberfit_current_role()) = 'admin'::public.iberfit_role) with check ((select public.iberfit_current_role()) = 'admin'::public.iberfit_role);
create policy client_timeline_admin_delete on public.client_timeline_events for delete to authenticated using ((select public.iberfit_current_role()) = 'admin'::public.iberfit_role);
drop policy if exists receipts_actor_read on public.outbox_receipts;
create policy receipts_actor_read on public.outbox_receipts for select to authenticated using (actor_user_id = (select auth.uid()) or (select public.iberfit_role()) = 'admin'::public.iberfit_role);;
