create index if not exists idx_consent_notice_id on public.consent_acceptances_v17(notice_id);
drop policy if exists beta_participants_admin_write on public.beta_participants_v16;
create policy beta_participants_admin_insert on public.beta_participants_v16 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy beta_participants_admin_update on public.beta_participants_v16 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy beta_participants_admin_delete on public.beta_participants_v16 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists feature_flags_admin_write on public.feature_flags_v18;
create policy feature_flags_admin_insert on public.feature_flags_v18 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy feature_flags_admin_update on public.feature_flags_v18 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy feature_flags_admin_delete on public.feature_flags_v18 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists incident_staff_write on public.incident_register_v17;
create policy incident_staff_insert on public.incident_register_v17 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role or owner_id=(select auth.uid()));
create policy incident_staff_update on public.incident_register_v17 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role or owner_id=(select auth.uid())) with check((select public.iberfit_role())='admin'::public.iberfit_role or owner_id=(select auth.uid()));
create policy incident_staff_delete on public.incident_register_v17 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists preview_sessions_admin_write on public.preview_sessions;
create policy preview_sessions_admin_insert on public.preview_sessions for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy preview_sessions_admin_update on public.preview_sessions for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy preview_sessions_admin_delete on public.preview_sessions for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists privacy_notice_admin_write on public.privacy_notices_v17;
create policy privacy_notice_admin_insert on public.privacy_notices_v17 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy privacy_notice_admin_update on public.privacy_notices_v17 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy privacy_notice_admin_delete on public.privacy_notices_v17 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists release_candidates_admin on public.release_candidates;
create policy release_candidates_admin_insert on public.release_candidates for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy release_candidates_admin_update on public.release_candidates for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy release_candidates_admin_delete on public.release_candidates for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists rollout_plans_admin_all on public.rollout_plans_v18;
create policy rollout_plans_admin_insert on public.rollout_plans_v18 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_plans_admin_update on public.rollout_plans_v18 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_plans_admin_delete on public.rollout_plans_v18 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists rollout_waves_admin_write on public.rollout_waves_v18;
create policy rollout_waves_admin_insert on public.rollout_waves_v18 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_waves_admin_update on public.rollout_waves_v18 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_waves_admin_delete on public.rollout_waves_v18 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);
drop policy if exists rollout_metrics_admin_write on public.rollout_metrics_v18;
create policy rollout_metrics_admin_insert on public.rollout_metrics_v18 for insert to authenticated with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_metrics_admin_update on public.rollout_metrics_v18 for update to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role) with check((select public.iberfit_role())='admin'::public.iberfit_role);
create policy rollout_metrics_admin_delete on public.rollout_metrics_v18 for delete to authenticated using((select public.iberfit_role())='admin'::public.iberfit_role);;
