drop policy if exists user_profiles_self on public.user_profiles;
create policy user_profiles_self on public.user_profiles for select to authenticated using (user_id = (select auth.uid()) or (select public.iberfit_role()) = 'admin'::public.iberfit_role);
drop policy if exists assignments_admin_coach_read on public.client_assignments;
create policy assignments_admin_coach_read on public.client_assignments for select to authenticated using (coach_user_id = (select auth.uid()) or (select public.iberfit_role()) = 'admin'::public.iberfit_role);
drop policy if exists clients_read on public.clients;
drop policy if exists clients_write_coach on public.clients;
create policy clients_read on public.clients for select to authenticated using (id = (select public.iberfit_client_id()) or public.is_assigned_coach(id));
create policy clients_insert_coach on public.clients for insert to authenticated with check (public.is_assigned_coach(id));
create policy clients_update_coach on public.clients for update to authenticated using (public.is_assigned_coach(id)) with check (public.is_assigned_coach(id));
create policy clients_delete_coach on public.clients for delete to authenticated using (public.is_assigned_coach(id));
drop policy if exists profiles_read on public.client_app_profiles;
drop policy if exists profiles_write on public.client_app_profiles;
create policy profiles_read on public.client_app_profiles for select to authenticated using (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and status = 'publicado'::public.publication_status));
create policy profiles_insert_coach on public.client_app_profiles for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy profiles_update_coach on public.client_app_profiles for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy profiles_delete_coach on public.client_app_profiles for delete to authenticated using (public.is_assigned_coach(client_id));
drop policy if exists cycles_read on public.training_cycles;
drop policy if exists cycles_write on public.training_cycles;
create policy cycles_read on public.training_cycles for select to authenticated using (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and status = 'publicado'::public.publication_status));
create policy cycles_insert_coach on public.training_cycles for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy cycles_update_coach on public.training_cycles for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy cycles_delete_coach on public.training_cycles for delete to authenticated using (public.is_assigned_coach(client_id));
drop policy if exists sessions_read on public.sessions;
drop policy if exists sessions_write on public.sessions;
create policy sessions_read on public.sessions for select to authenticated using (public.is_assigned_coach(client_id) or (client_id = (select public.iberfit_client_id()) and status = 'publicado'::public.publication_status));
create policy sessions_insert_coach on public.sessions for insert to authenticated with check (public.is_assigned_coach(client_id));
create policy sessions_update_coach on public.sessions for update to authenticated using (public.is_assigned_coach(client_id)) with check (public.is_assigned_coach(client_id));
create policy sessions_delete_coach on public.sessions for delete to authenticated using (public.is_assigned_coach(client_id));;
