const NAME_OVERRIDES=Object.freeze({
  "Ab wheel desde rodillas": "Rueda abdominal desde rodillas",
  "Air bike": "Bicicleta de aire",
  "Battle ropes alternas": "Cuerdas ondulatorias alternas",
  "Battle ropes dobles": "Cuerdas ondulatorias simultáneas",
  "Bear crawl": "Gateo del oso",
  "Bear plank": "Plancha en cuadrupedia",
  "Bear plank shoulder tap": "Plancha en cuadrupedia con toque de hombro",
  "Bird dog": "Extensión cruzada en cuadrupedia",
  "Bird dog con banda": "Extensión cruzada en cuadrupedia con banda",
  "Bird dog con pausa": "Extensión cruzada en cuadrupedia con pausa",
  "Body saw": "Sierra corporal",
  "Bottom-up press con kettlebell": "Empuje con pesa rusa invertida",
  "Bound lateral controlado": "Salto lateral amplio controlado",
  "Box jump": "Salto al cajón",
  "Box jump bajo": "Salto a cajón bajo",
  "Burpee": "Secuencia de plancha y salto",
  "Burpee sin salto": "Secuencia de plancha sin salto",
  "CARs de cadera": "Rotaciones articulares controladas de cadera",
  "CARs de hombro": "Rotaciones articulares controladas de hombro",
  "Cable pull through unilateral": "Tracción unilateral entre piernas en polea",
  "Cat-cow": "Gato-vaca",
  "Child pose con alcance lateral": "Postura del niño con alcance lateral",
  "Chin tuck": "Retracción cervical",
  "Chop alto a bajo": "Rotación diagonal de arriba abajo",
  "Clamshell": "Apertura de cadera en decúbito lateral",
  "Clamshell con banda": "Apertura de cadera en decúbito lateral con banda",
  "Copenhagen plank corto": "Plancha de Copenhague corta",
  "Copenhagen plank largo": "Plancha de Copenhague larga",
  "Cossack flow asistido": "Secuencia cosaca asistida",
  "Crunch abdominal": "Encogimiento abdominal",
  "Crunch en polea": "Encogimiento abdominal en polea",
  "Curl inclinado con mancuernas": "Flexión de bíceps en banco inclinado con mancuernas",
  "Curl martillo": "Flexión martillo de bíceps",
  "Curl predicador": "Flexión de bíceps en banco predicador",
  "Curtsy lunge": "Zancada cruzada",
  "Dead bug": "Insecto muerto",
  "Dead bug con banda": "Insecto muerto con banda",
  "Dead bug con fitball": "Insecto muerto con balón de estabilidad",
  "Devil press": "Secuencia de plancha y empuje con mancuernas",
  "Extensión torácica sobre foam roller": "Extensión torácica sobre rodillo de espuma",
  "Face pull": "Tirón hacia la cara",
  "Face pull con banda": "Tirón hacia la cara con banda",
  "Farmer carry": "Paseo del granjero",
  "Floor press con barra": "Empuje de pecho en suelo con barra",
  "Floor press con mancuernas": "Empuje de pecho en suelo con mancuernas",
  "Foam roll cuádriceps": "Automasaje de cuádriceps con rodillo",
  "Foam roll dorsal ancho": "Automasaje del dorsal ancho con rodillo",
  "Foam roll gemelos": "Automasaje de gemelos con rodillo",
  "Foam roll isquiotibiales": "Automasaje de isquiotibiales con rodillo",
  "Front rack carry": "Transporte frontal con pesas rusas",
  "Hack squat": "Sentadilla en máquina inclinada",
  "Handstand hold asistido": "Equilibrio de manos isométrico asistido",
  "Hip hinge con saco": "Bisagra de cadera con saco",
  "Hip thrust con banda": "Empuje de cadera con banda",
  "Hip thrust con barra": "Empuje de cadera con barra",
  "Hip thrust con peso corporal": "Empuje de cadera con peso corporal",
  "Hip thrust unilateral": "Empuje de cadera unilateral",
  "Hollow hold": "Posición hueca isométrica",
  "Hollow hold regresado": "Posición hueca isométrica adaptada",
  "Hollow rocks": "Balanceos en posición hueca",
  "Jerk técnico con palo": "Envión técnico con palo",
  "Kettlebell swing": "Balanceo con pesa rusa",
  "L-sit asistido": "Sentado en L asistido",
  "Landmine rotation": "Rotación con barra anclada",
  "Lat prayer en polea": "Jalón de brazos rectos arrodillado en polea",
  "Lift bajo a alto": "Elevación diagonal de abajo arriba",
  "Lunge lateral": "Zancada lateral",
  "Lunge lateral con mancuerna": "Zancada lateral con mancuerna",
  "Med ball slam": "Lanzamiento de balón medicinal al suelo",
  "Monster walk": "Caminata en semisentadilla con banda",
  "Mountain climber": "Escalador",
  "Mountain climber lento": "Escalador lento",
  "Nordic hamstring asistido": "Flexión nórdica de isquiotibiales asistida",
  "Nordic hamstring excéntrico": "Flexión nórdica excéntrica de isquiotibiales",
  "Open book": "Libro abierto",
  "Overhead carry unilateral": "Transporte unilateral sobre la cabeza",
  "Pallof press con paso lateral": "Empuje Pallof con paso lateral",
  "Pallof press de pie": "Empuje Pallof de pie",
  "Pallof press en polea": "Empuje Pallof en polea",
  "Pallof press medio arrodillado": "Empuje Pallof medio arrodillado",
  "Pallof press overhead": "Empuje Pallof sobre la cabeza",
  "Peso muerto kettlebell desde el suelo": "Peso muerto con pesa rusa desde el suelo",
  "Peso muerto landmine": "Peso muerto con barra anclada",
  "Pike push-up": "Flexión en pica",
  "Pike push-up elevada": "Flexión en pica elevada",
  "Pinch grip con discos": "Pinza de agarre con discos",
  "Pistol squat a cajón": "Sentadilla a una pierna hasta cajón",
  "Pistol squat asistida con TRX": "Sentadilla a una pierna asistida con TRX",
  "Pogo jumps": "Saltos reactivos de tobillo",
  "Press Arnold": "Empuje Arnold",
  "Press francés con barra EZ": "Extensión francesa de tríceps con barra EZ",
  "Press landmine bilateral": "Empuje bilateral con barra anclada",
  "Press landmine de pie": "Empuje de pie con barra anclada",
  "Press landmine medio arrodillado": "Empuje medio arrodillado con barra anclada",
  "Press landmine unilateral": "Empuje unilateral con barra anclada",
  "Prone cobra": "Cobra en decúbito prono",
  "Pull through en polea": "Tracción entre piernas en polea",
  "Pullover con banda": "Extensión de hombros con banda",
  "Pullover con mancuerna": "Extensión de hombros con mancuerna",
  "Pullover en polea": "Extensión de hombros en polea",
  "Push press con barra": "Empuje de hombros con impulso y barra",
  "Push press con mancuernas": "Empuje de hombros con impulso y mancuernas",
  "Push-up plus": "Flexión escapular",
  "Push-up plus en pared": "Flexión escapular en pared",
  "Remo T-bar": "Remo con barra T",
  "Remo gorila con kettlebell": "Remo gorila con pesa rusa",
  "Remo landmine unilateral": "Remo unilateral con barra anclada",
  "Renegade row": "Remo en plancha con mancuernas",
  "Renegade row apoyado": "Remo en plancha apoyada con mancuernas",
  "Reverse crunch": "Encogimiento abdominal inverso",
  "Reverse hyper": "Hiperextensión inversa",
  "Reverse lunge desde déficit": "Zancada atrás desde desnivel",
  "Rock back de aductores": "Balanceo hacia atrás de aductores",
  "Salto en split squat": "Salto en posición de zancada",
  "Scaption con mancuernas": "Elevación en plano escapular con mancuernas",
  "Seal row": "Remo con pecho apoyado en banco",
  "Sentadilla Cossack": "Sentadilla cosaca",
  "Sentadilla Cossack asistida": "Sentadilla cosaca asistida",
  "Sentadilla Goblet": "Sentadilla en copa",
  "Sentadilla Goblet con pausa": "Sentadilla en copa con pausa",
  "Sentadilla Goblet tempo 3-1-1": "Sentadilla en copa con ritmo 3-1-1",
  "Sentadilla en multipower": "Sentadilla en máquina de barra guiada",
  "Sentadilla landmine": "Sentadilla con barra anclada",
  "Sentadilla landmine a cajón": "Sentadilla a cajón con barra anclada",
  "Sentadilla overhead con barra": "Sentadilla sobre la cabeza con barra",
  "Sentadilla overhead con palo": "Sentadilla sobre la cabeza con palo",
  "Sentadilla sissy asistida": "Sentadilla con inclinación posterior asistida",
  "Serratus wall slide": "Deslizamiento de serrato en pared",
  "Skater squat": "Sentadilla de patinador",
  "Skater squat asistida": "Sentadilla de patinador asistida",
  "SkiErg": "Ergómetro de esquí",
  "Skipping alto": "Carrera técnica con rodillas altas",
  "Skipping bajo": "Carrera técnica con rodillas bajas",
  "Sled drag hacia atrás": "Arrastre de trineo hacia atrás",
  "Sled push": "Empuje de trineo",
  "Spanish squat dinámica": "Sentadilla española dinámica",
  "Split squat": "Sentadilla en posición de zancada",
  "Split squat asistido": "Sentadilla asistida en posición de zancada",
  "Split squat con barra": "Sentadilla en posición de zancada con barra",
  "Split squat con mancuernas": "Sentadilla en posición de zancada con mancuernas",
  "Split squat isométrico": "Sentadilla isométrica en posición de zancada",
  "Squeeze press con mancuernas": "Empuje de pecho con mancuernas juntas",
  "Step-down frontal": "Bajada frontal controlada del cajón",
  "Step-down lateral": "Bajada lateral controlada del cajón",
  "Step-up alto": "Subida a cajón alto",
  "Step-up bajo": "Subida a cajón bajo",
  "Step-up con impulso de rodilla": "Subida al cajón con impulso de rodilla",
  "Step-up lateral": "Subida lateral al cajón",
  "Step-up medio": "Subida a cajón medio",
  "Stir the pot": "Círculos sobre balón de estabilidad",
  "Straight-arm pulldown": "Jalón con brazos rectos",
  "Suitcase carry": "Transporte unilateral tipo maleta",
  "Suitcase hold": "Sujeción unilateral tipo maleta",
  "Thruster con mancuernas": "Sentadilla con empuje sobre la cabeza y mancuernas",
  "Tibialis raise en pared": "Elevación de tibial anterior en pared",
  "Turkish get-up completo": "Levantamiento turco completo",
  "Turkish get-up parcial": "Levantamiento turco parcial",
  "Wall angel": "Deslizamiento de brazos en pared",
  "Wall sit": "Sentadilla isométrica en pared",
  "Zancada en multipower": "Zancada en máquina de barra guiada",
  "Wall slide": "Deslizamiento en pared",
  "Z press con mancuernas": "Empuje Z con mancuernas"
});

const EQUIPMENT_LABELS=Object.freeze({
  'air bike':'bicicleta de aire',
  fitball:'balón de estabilidad',
  'foam roller':'rodillo de espuma',
  grip:'ejercitador de agarre',
  kettlebell:'pesa rusa',
  landmine:'barra anclada',
  'ski erg':'ergómetro de esquí',
  'trap bar':'barra hexagonal',
});

const GENERIC_REPLACEMENTS=Object.freeze([
  [/\bkettlebell\b/gi,'pesa rusa'],
  [/\btrap bar\b/gi,'barra hexagonal'],
  [/\blandmine\b/gi,'barra anclada'],
  [/\bfitball\b/gi,'balón de estabilidad'],
  [/\bfoam roller\b/gi,'rodillo de espuma'],
  [/\btempo\b/gi,'ritmo'],
  [/\boverhead\b/gi,'sobre la cabeza'],
  [/\bpress\b/gi,'empuje'],
  [/\bcurl\b/gi,'flexión'],
]);

export const EXERCISE_VISIBLE_FORBIDDEN_TERMS=Object.freeze([
  'clamshell','monster walk','pinch grip','ab wheel','bear plank','body saw','dead bug','hollow hold','hollow rocks',
  'mountain climber','stir the pot','overhead carry','suitcase carry','suitcase hold','bird dog','pull through','hip hinge','hip thrust',
  'kettlebell','nordic hamstring','reverse hyper','cat-cow','child pose','chin tuck','air bike','floor press','squeeze press',
  'bottom-up','handstand hold','jerk','pike push-up','push press','scaption','turkish get-up','prone cobra','push-up',
  'wall slide','curl','crunch','burpee','devil press','thruster','bear crawl','farmer carry','front rack','skipping','sled',
  'rock back','open book','battle ropes','med ball','foam roll','chop','box jump','pogo jumps','hack squat','goblet',
  'spanish squat','wall sit','tibialis raise','face pull','renegade row','seal row','lat prayer','pullover','straight-arm',
  'bound lateral','curtsy lunge','lunge','pistol squat','skater squat','split squat','step-up','step-down','landmine','fitball',
  'trap bar','multipower','tempo'
]);

function capitalise(value=''){const text=String(value||'').trim();return text?text.charAt(0).toLocaleUpperCase('es-ES')+text.slice(1):text;}
export function castilianExerciseName(name){
  const original=String(name||'').trim();
  let translated=NAME_OVERRIDES[original]||original;
  for(const [pattern,replacement] of GENERIC_REPLACEMENTS)translated=translated.replace(pattern,replacement);
  return capitalise(translated);
}
export function castilianExerciseEquipment(value){
  const original=String(value||'').trim();
  return EQUIPMENT_LABELS[original.toLowerCase()]||original;
}
export function localiseExerciseForDisplay(raw={}){
  const originalName=String(raw?.name_es||'').trim();
  const originalEquipment=String(raw?.equipment||'').trim();
  const translatedName=castilianExerciseName(originalName);
  const translatedEquipment=castilianExerciseEquipment(originalEquipment);
  const aliases=[...(Array.isArray(raw?.aliases)?raw.aliases:[])];
  if(originalName&&originalName!==translatedName&&!aliases.includes(originalName))aliases.push(originalName);
  if(originalEquipment&&originalEquipment!==translatedEquipment&&!aliases.includes(originalEquipment))aliases.push(originalEquipment);
  return {...raw,name_es:translatedName,equipment:translatedEquipment,original_name_es:originalName,original_equipment:originalEquipment,aliases};
}
