import {detectWearableBridge,normalizeWearableProvider} from './contracts.js';
import {deduplicateWearableDailyRecords,normalizeWearableDailyRecord} from './normalization.js';
const READ_SCOPES=Object.freeze(['steps','activeMinutes','sleepMinutes','restingHeartRate','hrvMs','activeEnergyKcal','workoutMinutes']);
const NATIVE_PROVIDERS=Object.freeze(['apple_health','health_connect','samsung_health','wear_os_health_services','ble_direct']);
function client(value){const id=String(value||'').trim();if(!id)throw new Error('M26_WEARABLE_CLIENT_REQUIRED');return id;}
function adapterFor(scope,provider){const normalized=normalizeWearableProvider(provider),common=scope?.IBERFIT_HEALTH_BRIDGE,device=scope?.IBERFIT_DEVICE_BRIDGE;if(normalized==='apple_health')return common?.appleHealth||null;if(['health_connect','samsung_health'].includes(normalized))return common?.healthConnect||scope?.AndroidHealthBridge||null;if(normalized==='wear_os_health_services')return common?.healthServices||null;if(normalized==='ble_direct')return common?.ble||device?.ble||null;return null;}
function requireMethod(adapter,name){if(typeof adapter?.[name]!=='function')throw new Error('M26_WEARABLE_NATIVE_BRIDGE_UNAVAILABLE');return adapter[name].bind(adapter);}
function supportKey(provider){const normalized=normalizeWearableProvider(provider);if(normalized==='apple_health')return 'appleHealth';if(['health_connect','samsung_health'].includes(normalized))return 'healthConnect';if(normalized==='wear_os_health_services')return 'healthServices';if(normalized==='ble_direct')return 'bleDirect';return null;}
export function createWearableBridgeService({scope=globalThis}={}){const support=detectWearableBridge(scope);function providerSupport(provider){const key=supportKey(provider);return key?support[key]:Object.freeze({available:false,reason:'M26_WEARABLE_NATIVE_BRIDGE_UNAVAILABLE'});}function isAvailable(provider){return providerSupport(provider).available===true;}async function requestAuthorization({provider,clientId,scopes=READ_SCOPES}={}){const id=client(clientId),adapter=adapterFor(scope,provider),request=requireMethod(adapter,'requestAuthorization'),allowed=[...new Set((Array.isArray(scopes)?scopes:[]).filter((item)=>READ_SCOPES.includes(item)))];if(!allowed.length)throw new Error('M26_WEARABLE_SCOPE_REQUIRED');const result=await request({clientId:id,scopes:allowed});return Object.freeze({provider:normalizeWearableProvider(provider),clientId:id,granted:Array.isArray(result?.granted)?result.granted.filter((item)=>allowed.includes(item)):[],requested:allowed});}async function readDailySummaries({provider,clientId,startDate,endDate}={}){const id=client(clientId),adapter=adapterFor(scope,provider),read=requireMethod(adapter,'readDailySummaries'),rows=await read({clientId:id,startDate,endDate,metrics:READ_SCOPES});if(!Array.isArray(rows))throw new Error('M26_WEARABLE_BRIDGE_RESPONSE_INVALID');const normalized=[];for(const row of rows){const result=normalizeWearableDailyRecord(row,{clientId:id,provider});if(result.ok&&result.value.clientId===id)normalized.push(result.value);}return Object.freeze(deduplicateWearableDailyRecords(normalized));}async function setSyncEnabled({provider,clientId,enabled}={}){const id=client(clientId),adapter=adapterFor(scope,provider);if(typeof adapter?.setSyncEnabled!=='function')return Object.freeze({provider:normalizeWearableProvider(provider),clientId:id,enabled:Boolean(enabled)});const result=await adapter.setSyncEnabled({clientId:id,enabled:Boolean(enabled)});return Object.freeze({provider:normalizeWearableProvider(provider),clientId:id,enabled:Boolean(result?.enabled)});}return Object.freeze({support,providerSupport,isAvailable,requestAuthorization,readDailySummaries,setSyncEnabled,readScopes:READ_SCOPES,nativeProviders:NATIVE_PROVIDERS});}
